### ISSUE TITLE
globes.co.il (??)

### ISSUE THREAD

**Issue by adkiller126** [easylist/EasyListHebrew#161]
**ADS ARE STILL HERE (!!)** 

I really do not understand why you have closed this issue???

Please block: 

- **com*$script,subdocument,third-party,domain=globes.co.il**
- beerforthepipl,com

In addition, please contact me via email adkiller126@gmail.com if you're interested in a better idea hoe to deal with it. 

![globes](https://cloud.githubusercontent.com/assets/19250084/15780403/2281931c-29aa-11e6-8088-ae8eed2603d5.png)

**Comment by IsraeliUser** [comment]
There were some issues with Github.
Try using uBlock Origin.

**Comment by freeinternet16** [comment]
@IsraeliUser 
A bit strange.. I do not understand what is the problem is to add the filter rules?
Globes **full of very intrusive ads**... and you can solve it easily. 
About the GitHub - what is the difference between your last updated you made for Mako?

**Comment by IsraeliUser** [comment]
I see no ads.

**Comment by freeinternet16** [comment]
Please block them. Thanks. 

http://www.globes.co.il/news/article.aspx?did=1001129604#fromelement=hp_folders_594

![2](https://cloud.githubusercontent.com/assets/17808973/15804243/dba33a2e-2b0a-11e6-9181-56c7187e3b4b.PNG)
![capture](https://cloud.githubusercontent.com/assets/17808973/15804244/dba3bc1a-2b0a-11e6-8b81-d1be25c2b885.PNG)
![capture1](https://cloud.githubusercontent.com/assets/17808973/15804245/dba4c7cc-2b0a-11e6-81c2-a7832718f288.PNG)

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/29b7d4bd5ca79a85c4b6e9a09990c269afc140ad

**Comment by freeinternet16** [comment]
Thanks!
