### ISSUE TITLE
Ads on globes/ ynet / mako / bizportal 

### ISSUE THREAD

**Issue by freeinternet16** [easylist/EasyListHebrew#162]
@EasyListIsrael @IsraeliUser @EasyListHebrew 

Please add this rule: 

`.com/*?*=$script,subdocument,xmlhttprequest,third-party,domain=bizportal.co.il|globes.co.il|mako.co.il|ynet.co.il`

![image](https://cloud.githubusercontent.com/assets/17808973/15854301/e0122e78-2cb1-11e6-94de-210926b4e289.png)

**Comment by adkiller126** [comment]
@EasyListIsrael @EasyListHebrew  - please add the rule above. 

In addition - see below the "untouchableads.com"  domains list [block them as well]

bakkels.com
bargainpricedude.com
beerforthepipl.com
benchmarkingstuff.com
bostonparadise.com
bostonwall.com
bulgarine.com
corruptcy.com
dascasdw.xyz
depresis.com
havinates.com
houstion.com
hulahooprect.com
indeterman.com
jacquarter.com
klnrew.site
kmrnkjer.xyz
loopmaze.com
newyorkwhil.com
njkiho.info
nothering.com
nullenabler.com
numberthreebear.com
oversailor.com
retrayan.com
sprawley.com
yathmoth.com
