### ISSUE TITLE
The Marker

### ISSUE THREAD

**Issue by freeinternet16** [easylist/EasyListHebrew#164]
For Banners:
`www.themarker.com##a[href^="http://rmkz.themarker.com/gampad/clk"]`
For Outbrain: 
`www.themarker.com##a[onmousedown*="this.href='http://paid.outbrain.com"]`

![image](https://cloud.githubusercontent.com/assets/17808973/15937500/d9767250-2e77-11e6-850d-b5b874b87195.png)

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/b2e293966a00020826dc4e05591ae7a18edf6f11 https://github.com/easylist/EasyListHebrew/commit/ef4fd5456743e68fb0268089f2e7d9d1aa146566
