### ISSUE TITLE
Ads in mako.co.il are not blocked with uBO

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#165]
Hello,

Using Firefox 47 + uBO, most ads in http://www.mako.co.il/news-specials/today-in-history-q2_2016/Article-5f20ae33a314551004.htm?Partner=rss are not blocked.

Thank you.

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/8475727f0535a5574f124d88399275d4a8e18653

**Comment by Yaron10** [comment]
Hello Yuval,

Thank you. I appreciate your work.

What about the banners at top and bottom?

BR

**Comment by IsraeliAdblocker** [comment]
please update your filters, I can't see any banners.

**Comment by Yaron10** [comment]
I've updated the filters.
http://s33.postimg.org/l8srs8clr/image.png

Thanks again.
