### ISSUE TITLE
mako ads

### ISSUE THREAD

**Issue by freeinternet16** [easylist/EasyListHebrew#166]
domain - gitcdn.pw
add - pw^$domain=mako.co.il,third-party

@IsraeliUser  - we need better regex here or **I suggest we should block any 3rd party domain** except domain we approve. 

![image](https://cloud.githubusercontent.com/assets/17808973/16034778/4d1de92a-321c-11e6-91bf-9bd3813d7d89.png)

**Comment by freeinternet16** [comment]
They've added a new subdomain - https://bok.gover.download/i1vkfxie
And, please block the Outbrain Ads (same technique here - changing domains)

![image](https://cloud.githubusercontent.com/assets/17808973/16073705/ddb169f2-32ef-11e6-97c3-abf6c2c27fe4.png)

![image](https://cloud.githubusercontent.com/assets/17808973/16073746/1b21554a-32f0-11e6-94ac-9c2a3f0c3dac.png)

**Comment by adkiller126** [comment]
No Problem - Just add `*$subdocument,third-party,domain=mako.co.il` 
And, of course, you can do some white listed for an essential services after that.

**Comment by IsraeliAdblocker** [comment]
Outbrain ads are unrelated, Outbrain ads for Mako are on the "acceptable ads" program, if you do not want to see them, please disable "acceptable ads" in your extension.

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/fd800eebadde02d6c7064751b45d9741dbdd3654
