### ISSUE TITLE
The home page  of www.tapuz.co.il does not load properly

### ISSUE THREAD

**Issue by eladts** [easylist/EasyListHebrew#169]
The home page of www.tapuz.co.il does not load properly and remains mostly blank when ad-blocking is enabled. The home page renders fine when ad-blocking is disabled.

![image](https://cloud.githubusercontent.com/assets/6475871/16885456/a1d48710-4a9c-11e6-8bcb-f8d4708f74e0.png)

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/9084fc1186fb32088b9dab0b8cfe2a7966ed619b
