### ISSUE TITLE
[Regression] Many ads in ynet

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#170]
Hello,

http://www.ynet.co.il/home/0,7340,L-5363,00.html

Thanks.

**Comment by almog123** [comment]
https://goo.gl/Dke2YS ???

**Comment by Yaron10** [comment]
Firefox 47.
uBO 1.6.7.

Just updated all lists.

https://s31.postimg.org/5bsyu2vh7/image.png

**Comment by Yaron10** [comment]
https://github.com/easylist/EasyListHebrew/commit/421f3240db1beccf9331e6c39f1dafa65a359bc6 has solved it.

Thank you.

**Comment by Yaron10** [comment]
Hello,

The filters to http://www.ynet.co.il/home/0,7340,L-5363,00.html should be updated.

Thank you.

**Comment by Yaron10** [comment]
Thank you. I appreciate it.

**Comment by Yaron10** [comment]
Again. :)

Thank you.

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/24df1b5bdcab833bdbc734531724318dad930399

**Comment by Yaron10** [comment]
@IsraeliUser,

Thank you. I appreciate it.

BR

**Comment by Yaron10** [comment]
Again. :)

Thank you.
