### ISSUE TITLE
Outbrain - calcalist

### ISSUE THREAD

**Issue by freeinternet16** [easylist/EasyListHebrew#171]
From some reason outbrain ads works on calcalist :(

Of course, when the Hebrew list is enabled

 
![image](https://cloud.githubusercontent.com/assets/17808973/17104734/dfc6324c-528c-11e6-9687-6d24fb38bcc4.png)

**Comment by IsraeliAdblocker** [comment]
I've checked both chrome and firefox, no ads out there. please update your filters.

**Comment by IsraeliAdblocker** [comment]
I've added an extra filters in any case.

**Comment by freeinternet16** [comment]
it still not working
please add -
