### ISSUE TITLE
outbrain - calcalist v2

### ISSUE THREAD

**Issue by freeinternet16** [easylist/EasyListHebrew#172]
it still not working - it might be caused by the generic hide
please add -

+calcalist.co.il,haaretz.co.il,themarker.com##a[href*="://paid.outbrain.com/network/redir?"][target="_blank"]
+calcalist.co.il,haaretz.co.il,themarker.com##a[onmousedown*="://paid.outbrain.com/network/redir?"][target="_blank"]

**Comment by IsraeliAdblocker** [comment]
please send a Firefox report.

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/9944fccd581a46df5431c680e54e0d3c6ade6f6f
