### ISSUE TITLE
Haaretz.co.il ads (multiple) no longer blocked ... and also on www.themarker.com

### ISSUE THREAD

**Issue by StentMan** [easylist/EasyListHebrew#173]
There are banners at the top of the page as well as ads on the sides of article pages (not on the front page).

These cosmetics filters seem to hide them. Couldn't figure out how to deal with them properly.
! 8/1/2016, 10:26:15 AM http://www.haaretz.co.il/news/politi/.premium-1.3024630
www.haaretz.co.il###top_banners
www.haaretz.co.il###new-haaretz\.co\.il\.web\.halfpage\.1
www.haaretz.co.il##body > .l-fluid:nth-of-type(8) > .has-l-fixed-column.l-wrapper > .l-main-wrapper > .l-main > .has-l-fixed-column.article > .h-group.has-l-article__entry > .l-article--sidebar > .ad
www.haaretz.co.il###new-haaretz\.co\.il\.web\.box\.1
www.haaretz.co.il###new-haaretz\.co\.il\.web\.box\.2

**Comment by StentMan** [comment]
Here's a page that demonstrates the problem that isn't behind the Haaretz' pay-wall:
http://www.haaretz.co.il/news/law/1.3019055

**Comment by StentMan** [comment]
Here's another bottom banner blocker:
www.haaretz.co.il###new-haaretz\.co\.il\.web\.promotionalcontentmedium\.1

**Comment by StentMan** [comment]
Sigh, and this page has some more ads that aren't blocked: http://www.haaretz.co.il/news
I'm going about this the wrong way. 
This does a very good job at removing the ads, although, leaving behind it ugly empty elements.
haaretz.co.il##a[href*="rmkz.themarker.com"]

**Comment by StentMan** [comment]
OK, it also helps with ads on www.themarker.com, for example on this page: http://www.themarker.com/wallstreet/1.3024359

My latest iteration is: www.haaretz.co.il,www.themarker.com##a[href*="rmkz.themarker.com"]

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/6fd7c99637d7618a4a5c989deea856009fd36cf0
