### ISSUE TITLE
I found a better way to handle those Haaretz/Themarker ads

### ISSUE THREAD

**Issue by StentMan** [easylist/EasyListHebrew#174]
Following up on #173, I think I figured out the script that loads all those ads, but it's difficult to fully test with the current rule set. At least for Haaretz it seems to work very well, but it may require some additional testing:
||haaretz.co.il/*/Houdini
||themarker.com/*/Houdini
That "should" replace that cosmetic rule, but it needs some more testing, especially on themarker, imho.

**Comment by IsraeliAdblocker** [comment]
the current rule is quite better, we can also add /houdini to save network time, but they could change it.

**Comment by IsraeliAdblocker** [comment]
done.

**Comment by StentMan** [comment]
Yes, I meant better in the sense that it saves traffic/time. Thank you!
Btw, do you ever remove old rules that are no longer relevant?

**Comment by IsraeliAdblocker** [comment]
yes we do, https://github.com/easylist/EasyListHebrew/commit/1a2b9b4d5021a370539c05ddba26b4a224b0347a
