### ISSUE TITLE
Ads on Ynet

### ISSUE THREAD

**Issue by freeinternet16** [easylist/EasyListHebrew#175]
Changing domains (looks similar like Mako) 
Using this domain: hik.ilovedomains.pw
**Please block any 3rd party domains again**

URL: http://www.ynet.co.il/articles/0,7340,L-4836210,00.html

**Comment by freeinternet16** [comment]
Ads with the Heb list of course

**Comment by IsraeliAdblocker** [comment]
@freeinternet16  why are you using two accounts? we really appreciate your help, but you don't need to use two accounts and open multiple tickets, we are working on this.

**Comment by freeinternet16** [comment]
Sorry.  @IsraeliAdblocker 
I just have two computers :)

**Comment by IsraeliAdblocker** [comment]
ads aren't there anymore.
