### ISSUE TITLE
פרסומות ב- YNET עם הרשימה העברית

### ISSUE THREAD

**Issue by adkiller126** [easylist/EasyListHebrew#176]
עמודים 

http://www.ynet.co.il/articles/0,7340,L-4838239,00.html
http://www.ynet.co.il/home/0,7340,L-6,00.html
מדומיין - https://hik.ilovedomains.pw/i1hxy26h/
![capture](https://cloud.githubusercontent.com/assets/19250084/17461265/ebaf2026-5c8e-11e6-8122-5dfac7da57df.PNG)
![aslkhjas](https://cloud.githubusercontent.com/assets/19250084/17461273/51127954-5c8f-11e6-98cc-c9e21b9fe70f.PNG)
![capture](https://cloud.githubusercontent.com/assets/19250084/17461274/51192b14-5c8f-11e6-8df0-a12dda55552d.PNG)

**Comment by IsraeliAdblocker** [comment]
fixed.
