### ISSUE TITLE
SeretHD.Net - האתר לא עובד עם העדכון אחרון

### ISSUE THREAD

**Issue by grandxx** [easylist/EasyListHebrew#178]
שלום, אני גולש באתר הזה באופן קבוע ולפתע גיליתי שכל האתר עם דף לבן ומעצבן.
ניסיתי הכל וכבר התקשרתי לספקית אינטרנט, ושום דבר לא עזר.
היום בדקתי את החוסם פרסומות וגיליתי שזו בעיה באחד מהמסננים פה, שהופך את כל הדף ללבן ואי אפשר לגלוש יותר באתר.
אשמח שתתקנו זאת במהירות.
http://serethd.net

Adblock gives white page problem with this website. Cant access and use the website anymore.

**Comment by IsraeliAdblocker** [comment]
the website is working well in both chrome and FF for me, which adblock you are using and which browser?

**Comment by grandxx** [comment]
Yes, for me
I'm pretty sure that everyone had this problem, because this site has a Chat and visitors started to complain the website is broken.
But i am just regular visitor and i cant check/tell if other still facing any issues.

**Comment by IsraeliAdblocker** [comment]
this was a wrong typo, fixed by israeliUser
