### ISSUE TITLE
AdBlock + Iframe

### ISSUE THREAD

**Issue by liorsh175** [easylist/EasyListHebrew#179]
Hi guys,
My name is Lior and im from mako website www.mako.co.il
We have few pages that include registration forms for Keshet Broadcast tv shows.
Those pages are build with Iframe component and we got blocked from your side. (maybe you see it as commercial)
Can you please check the links and disable the obstruction ?
Many thanks.

http://www.mako.co.il/music-24/eyal-gol ... =interlink
http://www.mako.co.il/food-masterchef/registration
http://www.mako.co.il/tv-bigbrother/audition
http://www.mako.co.il/tv-joinus/bake-off-israel
http://www.mako.co.il/tv-joinus/amazonas
http://www.mako.co.il/tv-music-school/registration
http://www.mako.co.il/tv-the-next-star/sign-up

**Comment by mapx-** [comment]
the first link:
http://www.mako.co.il/music-24/eyal-golan-audition?Partner=interlink

**Comment by liorsh175** [comment]
Thanks for your reply,
Do you mean that "the first link" is allowed ?
Thanks.

**Comment by mapx-** [comment]
no, I mean you published a wrong link :)

**Comment by liorsh175** [comment]
Now is it good - http://www.mako.co.il/music-24/eyal-golan-audition   ?

**Comment by mapx-** [comment]
probably that one with Partner=interlink is blocked (I simply copied it from the adblockplus forum where you first posted). Now, the easylist hebrew authors will tell you what they can do about.

**Comment by liorsh175** [comment]
I see.
So they will write to me here ?
and what about the other links ?
Thanks.

**Comment by mapx-** [comment]
Yes, here.
Probably you don't understand: when you post the links you simply copied an incomplete address. Look at the first link:
http://www.mako.co.il/music-24/eyal-gol ... =interlink
the correct link is:
http://www.mako.co.il/music-24/eyal-golan-audition?Partner=interlink

**Comment by liorsh175** [comment]
Thank you guys.
