### ISSUE TITLE
מאקו

### ISSUE THREAD

**Issue by Yoadx** [easylist/EasyListHebrew#183]
ברגע שאני פותח סרטון במאקו אני מקבל הודעה שהם חוסמים את אדבלוקר באתר ומפנים אותי ללינק להסרת אדבלוקר
סרטון:
https://www.youtube.com/watch?v=_2qr3p0XZCM&feature=youtu.be

When i'm opening a video in Mako.co.il i get a message that they're Blocking adblocker in the site and 
redicting me to a Adblocker-removal-tutorial

Video:
https://www.youtube.com/watch?v=_2qr3p0XZCM&feature=youtu.be

**Comment by IsraeliAdblocker** [comment]
can't reproduce with hebrew list. [chrome]
I don't have flash installed on firefox so I can't check.
this will solve your problem without hebrew list: `@@||akamai.advsnx.net/CDN/mako/mako.swf`
