### ISSUE TITLE
New domain used by mako.co.il for replacement ads (if adblock is detected)

### ISSUE THREAD

**Issue by smiley** [easylist/EasyListHebrew#186]
Looks like [mako](http://mako.co.il) started using adblock detection, which injects new ads with randomized element identifiers. The ads load off a new domain owned by "Aderz Media Ltd" (AKA "Uponit") : m[dot]cloodfront[dot]com. Blocking that domain entirely kills the adblock detector and the replaced ads.

**Comment by adkiller126** [comment]
@IsraeliAdblocker  please block any 3rd party domain there! 
Thanks

**Comment by IsraeliAdblocker** [comment]
they were already inside the Easylist (2 months ago), please use Hebrew List.

**Comment by smiley** [comment]
They aren't. `m.cloodfront.com` doesn't appear in [EasyListHebrew.txt](/easylist/EasyListHebrew/blob/847572ee0a1dbcce9506605de70eeb6951b361fa/EasyListHebrew.txt). (Which is why they weren't blocked despite already using the Hebrew list)

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/c9196ea90cb49d12b6c98d6ce2212247cb012ffa
Mako has whitelist to 3-rd party domains, cloodfront is not in the whitelist, that's why it's already blocked.

**Comment by smiley** [comment]
I checked again (without my blocking rule) and it's blocked now. I guess I had an old version cached. Sorry about that.
