### ISSUE TITLE
Videos won't play in http://www.kikar.co.il/

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#188]
Hello,

Videos won't play in http://www.kikar.co.il/ when uBO is enabled.
http://www.kikar.co.il/209291.html

Win 7, Firefox 48.02.

Thank you.

**Comment by IsraeliAdblocker** [comment]
I think that it is uBO related issue and not EasyListHebrew issue.

**Comment by Yaron10** [comment]
Thanks for replying.

The problem exists without uBO filters and also with ABP.
Does it work for you?

**Comment by Yaron10** [comment]
It's working now.
Please let me know if you have any idea as to the possible cause of the problem and the fix.

Thanks.
