### ISSUE TITLE
ynet new ads

### ISSUE THREAD

**Issue by yanivvv** [easylist/EasyListHebrew#194]
Hey, 

When using ynet:

http://www.ynet.co.il/articles/0,7340,L-4043984,00.html

I see ads from:

https://iystorage.com/

These ads are hiding everything, I can't even read the article.

Thanks.
Yaniv.

**Comment by adkiller126** [comment]
הי, פשוט תחסום כל צד שלישי שהוא לא מאושר...
third party)
המשחק הזה איתם ממש מיותר. 
תראה את זה - היתה חברה ששיחקה את המשחק הזה ב 2015
https://easylist.to/2015/08/19/issues-with-yavli-advertising.html
צריך ללמוד מהתגובה שלהם :)

**Comment by IsraeliAdblocker** [comment]
done, blocking every 3-rd party on the biggest site in isreal without creating tones of false positives is not easy to do.

**Comment by adkiller126** [comment]
please see my comment at #189
