### ISSUE TITLE
rotter.net

### ISSUE THREAD

**Issue by MrTal** [easylist/EasyListHebrew#196]
היי,
:שיש באתר, אבל ההודעה הזאת עדיין נשארה  Popups-ראיתי שאתמול טיפלתם ב
http://prntscr.com/cjwsf5
:אני ממליץ לחסום אותה גם, הפילטר חוסם אותה:
`rotter.net###tabptab > IMG
`

**Comment by IsraeliAdblocker** [comment]
I think that this kind of static ad is not bothering anyone, it is for charity also.

**Comment by MrTal** [comment]
ok,I understood
