### ISSUE TITLE
Ads on Walla! - changing domains

### ISSUE THREAD

**Issue by adkiller126** [easylist/EasyListHebrew#197]
Same guys like Ynet
http://b.walla.co.il/category/3054
http://b.walla.co.il/item/2998881
![0](https://cloud.githubusercontent.com/assets/19250084/18669324/21bc0a7c-7f43-11e6-88c7-d9801140f716.png)

**Comment by idan-hartzvi** [comment]
The new domain is wal.uvinory.com
please add the following rule to the list:
||wal.uvinory.com^$third-party

Thanks

**Comment by almog123** [comment]
https://goo.gl/M784Sc not good

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/808a9a91b42ee2820a82d2dd002abd37465e83bf

**Comment by adkiller126** [comment]
New domains- please add a generic rule- this game is useless
