### ISSUE TITLE
mako.co.il

### ISSUE THREAD

**Issue by shaygam22** [easylist/EasyListHebrew#200]
mako.co.il  a lots of ADS

**Comment by adkiller126** [comment]
see #201

**Comment by shaygam22** [comment]
But how do i block this fake domains:
jquerymin.co.il
jquerycdn.co.il

In MAXTHON browser please ???

בתאריך 15 באוק׳ 2016 21:35,‏ "adkiller126" <notifications@github.com> כתב:
