### ISSUE TITLE
Block Websocket + Base64 Ads (Mako, ynet..)

### ISSUE THREAD

**Issue by adkiller126** [easylist/EasyListHebrew#201]
In a very desperate way, these guys started to inject advertising with WebSocket and Base64.
Please Block the fake following domains -

jquerymin.co.il
jquerycdn.co.il

In general - this is a very good news... the fact they use WS + Base64 indicates that their position is very bad :)

**Comment by idan-hartzvi** [comment]
There is already a big discussion about it on #189 
The final understanding was that the rule `||www.ynet.co.il^$websocket,~third-party,domain=www.ynet.co.il` that already added, should fix it.
The reason why you still seeing thus ads are that adblock plus has some problematic support on WebSockets.
The good news is that they already fixes their problem in the development build,

So, there is three options:
1. Move to (or add) uBlock.
2. Move to ABP development build (at [)](https://adblockplus.org/en/development-builds#installation)
3. Wait a little until thus fix became official.

Let's see what they'll do in response ;)
