### ISSUE TITLE
www.geektime.co.il

### ISSUE THREAD

**Issue by idan-hartzvi** [easylist/EasyListHebrew#208]
Add the following rules to hide geektime new ads:
||geektime.co.il^$script
||geeklist.geektime.co.il^$domain=geektime.co.il

Thanks
Idan

**Comment by adkiller126** [comment]
Doesn't work for me.... seems the site is been block when this rule is enabled. 
see this: 

btw - I think ^script is too risky - we should find an elegant rule here. something we really can add to the general list.

**Comment by IsraeliUser** [comment]
They let you choose whether you want to block ads or not.

**Comment by MrTal** [comment]
have ads on the site now...

**Comment by almog123** [comment]
ads are still there

**Comment by ryanbr** [comment]
I can confirm there are ads on the site;

Most appropriate filter: geektime.co.il##A[href*="/wp-"][target="_blank"]

https://reports.adblockplus.org/224d163f-76bc-4f27-8293-59c517039aca

https://secure.fanboy.co.nz/geek.il-no-ads.png
https://secure.fanboy.co.nz/geek.il-ads.png

**Comment by IsraeliUser** [comment]
You can choose not to view ads by clicking on the _G_  on the bottom of the page.

**Comment by ryanbr** [comment]
If the **default** is to show Ads on site, and it **requires** a user to make said action, then Ads should be blocked. Not sure why list authors are making it difficult to block the site.

Its a site with ads, just block it. geez.

**Comment by ryanbr** [comment]
Thanks

**Comment by almog123** [comment]
ads are back again, they are now using random a hrefs. @ryanbr

**Comment by ryanbr** [comment]
`geektime.co.il##.banner
geektime.co.il##.sponsors-list
`

**Comment by almog123** [comment]
I suggest using: 
`||geektime.co.il/wp-includes/$image
@@||geektime.co.il/wp-includes/js/thickbox/loadingAnimation.gif`

because they will just use random class names in one day or so.

**Comment by adkiller126** [comment]
yep :(

@IsraeliUser 

btw - very high false positive right now with adblock - the `geektime.co.il##a[href*="/wp-"][target="_blank"] `rule is killing every image in the all article  

for example: http://www.geektime.co.il/eset-israel-ransock/  
adblcok:
![screen shot 2016-11-27 at 12 02 24 pm](https://cloud.githubusercontent.com/assets/19250084/20647300/9c155644-b499-11e6-9e46-39fafa689126.png)
no adblock
![screen shot 2016-11-27 at 12 03 37 pm](https://cloud.githubusercontent.com/assets/19250084/20647301/9ddb1536-b499-11e6-88d2-4dd62d9f205b.png)

**Comment by almog123** [comment]
I am sorry but ads are still there :(

**Comment by adkiller126** [comment]
@IsraeliAdblocker 

still high false potive 

![picture1](https://cloud.githubusercontent.com/assets/19250084/20647399/53cd94c0-b49c-11e6-9f05-619f18098550.png)

**Comment by IsraeliAdblocker** [comment]
@adkiller126 this is not true, this is still from the old rule of the HTML HREF, I've just checked it, there is a slight delay between a commit on the git and the time you can update the lists.
Please wait an hour and then force an update for your Hebrew list.

**Comment by adkiller126** [comment]
Yes. I see. thanks!
any case, for the long term we should find a better rules here. those are very risky rules.

**Comment by IsraeliAdblocker** [comment]
yes you are right, I love geektime.co.il and I hate to see that they are pushing us here, those risky rules are the best ones I could think of, if you have some suggestions, you can post them here.

**Comment by almog123** [comment]
ads are back.... please help us with that, I can't find any rule that will help here.

**Comment by almog123** [comment]
@ryanbr @IsraeliAdblocker @IsraeliUser

**Comment by DanIbba** [comment]
I'm working on it.
 
@almog123 - Hi dude, you sound a bit obsessed... :)
Just hit the red option for now.

**Comment by almog123** [comment]
It doesn't work, it was working but it somehow massed up, and now I am getting ads no matter what. 
btw, I am getting blank pages with adblock plus too sometimes... only when adblock is activated.

**Comment by DanIbba** [comment]
Works great for me...

**Comment by almog123** [comment]
![geek](https://cloud.githubusercontent.com/assets/17848148/20650986/a16024e4-b4e4-11e6-9841-1fdf3f9f4f82.png)

blank page....

**Comment by DanIbba** [comment]
Are you sure you don't have any custom rules??

**Comment by almog123** [comment]
you are right, I had one that is related to geektime..  `||geektime.co.il$xmlhttprequest`
it was working very well until today, now they have probably changed the code so it will cause a blank page.

**Comment by DanIbba** [comment]
Ok... you might miss up something.  We should find beer way.
P.S - maybe your custom rule interferes with the Red option- try to use it without any custom rules (works for me).  

Cool

**Comment by almog123** [comment]
looks like `||geektime.co.il$xmlhttprequest` makes a blank page with green option also.
they are expecting an answer from their XHR ads request, if there isn't an answer, they are doing
document.wirte(""); which makes the page empty.

**Comment by DanIbba** [comment]
@almog123 - again, just hit the Red button. it works great for me. 
 
good night

**Comment by almog123** [comment]
thanks for the help :) without the rule looks like it is working. (red button)

**Comment by DanIbba** [comment]
false positive 

https://geeklist.geektime.co.il/index_jobs_search3.php
https://geeklist.geektime.co.il/index_events.php

**Comment by adkiller126** [comment]
NICE!! 
You can remove: 

```
www.geektime.co.il/wp-content/uploads/[0-9]{0,4}/[0-9A-Z]{3,999}/$image,~third-party
||geektime.co.il/$xmlhttprequest
||geektime.co.il/wp-content/plugins/$image
||geektime.co.il/wp-includes/$image
```

**Comment by IsraeliAdblocker** [comment]
If I will remove those they will just change into another way to detect Adblock something that will pass genericHide rule, and then I will need to re-insert those rules again.
they will stay for now.

**Comment by adkiller126** [comment]
Yep. so, If I understand it right, you can keep only `||geektime.co.il/$xmlhttprequest` for now.

**Comment by adkiller126** [comment]
@IsraeliAdblocker @IsraeliUser 
ads are back. it's seems like they're using the ||geektime.co.il/$xmlhttprequest rule to detect Adblock.

**Comment by DanIbba** [comment]
@IsraeliUser @IsraeliAdblocker 
 what about the ads here?

**Comment by IsraeliAdblocker** [comment]
regex filter was removed, added hide filter for Firefox.
for Chrome they look like they are trying to "scam" us into removing the filters, the ads with hebrewlist are inline ads in a manner that they are always the same.
still trying to find a good filter for that.

**Comment by adkiller126** [comment]
ok. agree. 
you can remove as well - 
 ||geektime.co.il/wp-content/plugins/$image
 ||geektime.co.il/wp-includes/$image
and remove the xhr in order to remove their annoying jumping button. 

In general - I think the goal should be to block ads and not to punish them (think about it).

**Comment by adkiller126** [comment]
@IsraeliUser @IsraeliAdblocker 

**GREAT FALSE POSITIVE**

Please Remove Update 

![picture1](https://cloud.githubusercontent.com/assets/19250084/20865981/9bf91b1a-ba29-11e6-9cd1-dcc22cfdc300.png)

**Comment by moran-assaf360** [comment]
Hi guys, the ads still exists but like @adkiller126  mentioned the main image of the articles are gone,
I don't like to remove my Hebrew easy-list each time that I visit geektime please fix it!

**Comment by DanIbba** [comment]
@IsraeliAdblocker 
Hey. Still see ads on geektime with Chrome. Trying the rules that @moran-assaf360 suggested, I see no ads. Not understand why we  don't fix the issue.

**Comment by adkiller126** [comment]
Still see ads this morning with Chrome. 
I suggest to fix the problem with remove the xhr rule and see how things will work from there.

**Comment by ryanbr** [comment]
`geektime.co.il##[-abp-properties='data:']`
`geektime.co.il##.sponsors-list`

**Comment by adkiller126** [comment]
Hey 

It doesn't work, still see ads on Chrome with this rule... 
Only remove the xhr can help here. I spent hours to find another way, but right now this is the only way to avoid ads.

**Comment by moran-assaf360** [comment]
Hey @ryanbr 
It's doesn't work work for me as well,
Some times this rule damage the ads control icon, which is bad since I and any other user will not be able to opt out and choose to remove the ads.

**Comment by adkiller126** [comment]
Agree. The last thing you want to do is to keep ads and cancel the opt out option.

**Comment by ryanbr** [comment]
How about, (not fully tested for false positves).

`geektime.co.il##SCRIPT + A[href][target="_blank"]`
`geektime.co.il##ASIDE.sidebar:last-child > SECTION.widget[style]`
`geektime.co.il##ASIDE > .widget:first-child`
`geektime.co.il##[-abp-properties='data:']`
`geektime.co.il##.sponsors-list`

**Comment by adkiller126** [comment]
1. a lot of false positive. 
2. I don't like rules that using first/last child. They can easily put another dummy child to avoid it. 

Thanks!

**Comment by ryanbr** [comment]
The first filter should be okay then?

**Comment by ryanbr** [comment]
I view :first-child/last-child as valid filters imo, just another tool in the toolkit. Especially for sites where they're attempting to counter Adblock, Using any number of complex filters to counter them.

**Comment by adkiller126** [comment]
Unfortunately not. The first filter cause a lot of false positive.

**Comment by ryanbr** [comment]
`geektime.co.il##SCRIPT + A[href][target="_blank"]`

Does that help?

**Comment by adkiller126** [comment]
Looks good. 
I'm not familiar with this kind of rules, can you elaborate how does it work?

Btw - I still check false positive in other pages.

**Comment by IsraeliAdblocker** [comment]
looks like all of those suggestions aren't working.

the only thing that works is doing this:
`@@||ads.cxadserving.com^$domain=geektime.co.il
@@||geektime.co.il$generichide
geektime.co.il##.banner
geektime.co.il##.sponsors-list`

but that's will keep their AJAX requests free so they will fix this in no time, probably that's what they want so I won't push a fix that they could bypass easily.

**Comment by adkiller126** [comment]
Hey. 
Let's do it and see their next move. You always can re-insert this rule if its relevant. 
The main goal here is to BLOCK ADS, and now geektime is full of ads!

**Comment by IsraeliAdblocker** [comment]
I've found a better solution.

**Comment by adkiller126** [comment]
your last update?

**Comment by IsraeliAdblocker** [comment]
yes.

**Comment by moran-assaf360** [comment]
Hi, I still see ads the update didn't effected a ads ...

**Comment by adkiller126** [comment]
@IsraeliAdblocker 
Please put only hose rules on geektime:
@@||ads.cxadserving.com^$domain=geektime.co.il @@||geektime.co.il$generichide geektime.co.il##.banner geektime.co.il##.sponsors-list
And we see how to respond if they will try to take advantage the xhr removing.

**Comment by adkiller126** [comment]
@IsraeliAdblocker @IsraeliUser ??

**Comment by DanIbba** [comment]
Still see ads! please fix it. 
@adkiller126 @IsraeliAdblocker

**Comment by adkiller126** [comment]
Hi, unfortunately I have nothing to do with this. I already suggested what I believe we should have to do. 
From some reason we still see ads.

**Comment by idan-hartzvi** [comment]
I think that you can finally close this ticket.
It's look like they give up and they stops their stupid war against their users.

WE WON! (again)
