### ISSUE TITLE
Mako videos doesn't work with Add Blocker

### ISSUE THREAD

**Issue by YoYo06** [easylist/EasyListHebrew#209]
Hello,

I guess Mako did something so when you play a video on the website when the Ad Blocker is on, it doesn't load. 

I have tried both Agura and ABP on Chrome, both responded the same. 

Any idea how to bypass that?

![q1](https://cloud.githubusercontent.com/assets/22640964/20067770/29a4d05a-a51f-11e6-8283-5758a04fb426.JPG)

**Comment by IsraeliUser** [comment]
Can't reproduce.
