### ISSUE TITLE
mako.co.il new flash adds

### ISSUE THREAD

**Issue by exx8** [easylist/EasyListHebrew#210]
hi,
mako has added new flash adds in pages like this:
http://www.mako.co.il/news?partner=NavBar

![image](https://cloud.githubusercontent.com/assets/8540180/20494424/904f09b8-b025-11e6-8b1d-6e543b284191.png)

for more info, please comment.

**Comment by IsraeliAdblocker** [comment]
can't reproduce, I recommend using uBlock origin

**Comment by IsraeliAdblocker** [comment]
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

**Comment by exx8** [comment]
Please have a look here:
http://www.mako.co.il/news-channel2/Channel-2-Newscast-q4_2016/Article-69cf37920929851004.htm?sCh=86806603e7478110&pId=25483675
lots of ads.

**Comment by aaroncox31** [comment]
Not a single ad using uBlock origin
![2016-11-27_221632](https://cloud.githubusercontent.com/assets/13420968/20651501/4ae1ad76-b4ef-11e6-9338-41941764f6b3.jpg)

**Comment by exx8** [comment]
![image](https://cloud.githubusercontent.com/assets/8540180/20830152/dbfd8d20-b887-11e6-824b-8f2a578d04c0.png)
maybe you need to wait a few seconds, I've installed both ublock and adblock...

**Comment by IsraeliUser** [comment]
Use **uBlock Origin**, not uBlock.

**Comment by exx8** [comment]
Thank you. It's worked.
