### ISSUE TITLE
ads on walla

### ISSUE THREAD

**Issue by adkiller126** [easylist/EasyListHebrew#211]
they are trick the easylist with a 'whitelisted' domain (not acceptable ads)
the ad domain - umamdmo.com (already blocked)
the main easy list has a record of a whitelisted domain - comeadvertisewithus.com

they use sub domain called "comeadvertisewithus.com" for the domain "umamdmo.com" which generates this URL: https://comeadvertisewithus.com.umamdmo.com

it's seems like the Ad-Blocked can't obtain between the domain and the sub domain and since the whitelisted is stronger then the blacklisted. 

source: https://easylist.to/easylist/easylist.txt
<img width="915" alt="screen shot 2016-11-22 at 4 26 46 pm" src="https://cloud.githubusercontent.com/assets/19250084/20527334/a29c85ae-b0d0-11e6-89df-066ab18e1aca.png">

ads: 
![screen shot 2016-11-22 at 2 42 48 pm](https://cloud.githubusercontent.com/assets/19250084/20524781/cdf5f80e-b0c4-11e6-89ff-7b86fcfd6924.png)

**Comment by adkiller126** [comment]
Doesn't work for me 

I think this is a small bug on the extension.

**Comment by adkiller126** [comment]
Doesn't work for me

I think this is a small bug on the extension.

**Comment by IsraeliUser** [comment]
ABP doesn't support _$important_. Use uBlock Origin.

**Comment by IsraeliAdblocker** [comment]
no more ads there.
