### ISSUE TITLE
holyclock.co.il hijacking other sites on Sabbath

### ISSUE THREAD

**Issue by smiley** [easylist/EasyListHebrew#212]
Some websites embed a script from `holyclock.co.il` which hijack-redirects their site on weekends. (via `location.change` so the back button "breaks") While this is the intention of the site owners to "close" the website on Sabbath, it's an entire redirect and not a closeable notice like most websites do.

It's harder to ignore/dismiss than the usual page-hiding-notice, making it something worth considering for EasyList.

Blocking `holyclock.co.il` globally via uBlock Origin prevents that from happening (and doesn't produce any visible errors). You can test that out on [`telebox.co.il`](http://telebox.co.il).

**Comment by IsraeliAdblocker** [comment]
I don't agree, this isn't related to Hebrewlist, those are not ads, maybe it should go inside funboy annoying list.

**Comment by smiley** [comment]
Okay, I'll report this in fanboy's annoyance list
