### ISSUE TITLE
BizPortal

### ISSUE THREAD

**Issue by adkiller126** [easylist/EasyListHebrew#217]
Still see ads with the Hebrew list.

**Comment by ohadcn** [comment]
they are using cloudboost.co.il
for some reason cloudboost is blocked only ynet (for the maintainer: see my pull request, for everybody until he does: add `||cloudboost.co.il^` to your persunal ad blocking rules.

**Comment by adkiller126** [comment]
@IsraeliAdblocker  @IsraeliUser  ?
