### ISSUE TITLE
ynet: Video Player does not show up

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#224]
Hello,

http://www.ynet.co.il/articles/0,7340,L-4900064,00.html

Firefox 50.
uBO 1.10.4.

Thank you.

**Comment by Yaron10** [comment]
@IsraeliAdblocker,

The problem exists on all ynet pages.
Any idea?

Thank you.

**Comment by IsraeliAdblocker** [comment]
any suggestion for a fix? I can't figure out where the problem is, looks like a race with some of their JS

**Comment by Yaron10** [comment]
@IsraeliAdblocker,

Thank you for your work. 👍 I appreciate it.
