### ISSUE TITLE
Walla Video Ads

### ISSUE THREAD

**Issue by DanIbba** [easylist/EasyListHebrew#225]
http://news.walla.co.il/item/3026999

![screen shot 2016-12-29 at 13 14 03](https://cloud.githubusercontent.com/assets/24211092/21543293/73e02a12-cdcd-11e6-96ed-891e236df0b3.png)

**Comment by DanIbba** [comment]
using "blob:" + Base 64

**Comment by DanIbba** [comment]
Ads are still here @ryanbr @IsraeliAdblocker @IsraeliUser

**Comment by IsraeliUser** [comment]
Please provide a screenshot of uBO's logger.

**Comment by adkiller126** [comment]
I also see with ABP

**Comment by IsraeliUser** [comment]
We recommend uBlock Origin (uBO).

**Comment by adkiller126** [comment]
Thanks. Now block ads in adblock (still not in ABP) .

**Comment by adkiller126** [comment]
They use WebRTC. It's partly work.
