### ISSUE TITLE
פרסומות בקטעי וידאו - ynet

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#226]
http://www.ynet.co.il/articles/0,7340,L-4906383,00.html

Thank you.

**Comment by Yaron10** [comment]
Reproducible in Firefox 50 + uBO.

**Comment by YoYo06** [comment]
2 Problems in Ynet.....
1) Ads appear on some videos (see pic 1 below)
2) In many videos that are part of articles the video runs with sound only while the video screen in black. (see pic 2 below)

Pic 1:
![1](https://cloud.githubusercontent.com/assets/22640964/21957672/6e8f24b2-daa4-11e6-9184-816131cdece4.JPG)

Pic 2:
![2](https://cloud.githubusercontent.com/assets/22640964/21957674/7579449c-daa4-11e6-9902-d9259420d3a4.JPG)

Using Chrome, Win 10, ABP

**Comment by IsraeliAdblocker** [comment]
wrong whitelist filters, fixed now.

**Comment by Yaron10** [comment]
@IsraeliAdblocker,
Thank you very much. I appreciate it.
