### ISSUE TITLE
http://www.mako.co.il/mako-vod?partner=NavBar

### ISSUE THREAD

**Issue by MrTal** [easylist/EasyListHebrew#230]
Hey
have anti adblock in site: http://www.mako.co.il/mako-vod?partner=NavBar
exmple: http://www.mako.co.il/mako-vod-live-tv/VOD-5d3b3aeecbffc41006.htm?partner=hp-main
http://prntscr.com/dyn3mb

**Comment by EasyListHebrew** [comment]
@MrTal Hi I couldn't reproduce this, please send a full report 
what extension are you using? adblock adblock plus ublock?
what browser?

**Comment by MrTal** [comment]
now this work
