### ISSUE TITLE
yad2.co.il

### ISSUE THREAD

**Issue by Plazzmex** [easylist/EasyListHebrew#231]
Hi, 
yad2.co.il doesn't block ads on search pages.
For example: http://www.yad2.co.il/Nadlan/rent.php?multiSearch=1&City=%E4%F8%F6%EC%E9%E4&Neighborhood=&HomeTypeID=&fromRooms=1&untilRooms=&fromPrice=&untilPrice=&PriceType=1&FromFloor=&ToFloor=&fromSquareMeter=&untilSquareMeter=&Parking=1&Elevator=1&EnterDate=&Info=

Screenshot: http://prnt.sc/e188ar

On the main website page although everything is blocked.

Thanks

**Comment by IsraeliUser** [comment]
Fixed. Please use uBlock Origin.

**Comment by Plazzmex** [comment]
Started appearing again a week ago...
Using uBlock Origin

**Comment by DanIbba** [comment]
@IsraeliAdblocker @IsraeliUser 
I also see ads with ubo 

https://github.com/uBlockOrigin/uAssets/issues/329

**Comment by gorhill** [comment]
To save you time, this is the comment which contains the filter that works:
<https://github.com/uBlockOrigin/uAssets/issues/329#issuecomment-289134525>.

**Comment by ilyashk** [comment]
I have a problem when opening yad2 relevant advertisement, or maybe better to call it announcements.
If you are familiar with yad2 you'll know what I mean :)
Using AdNauseam
