### ISSUE TITLE
New Anti-AdBlock in www.inn.co.il

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#232]
Hello,

http://www.inn.co.il/News/News.aspx/339535

![image](https://cloud.githubusercontent.com/assets/10229320/22700650/099a85d8-ed64-11e6-95e6-93d5ad4e6ae2.png)

Thank you for your great work.

**Comment by Yaron10** [comment]
@IsraeliAdblocker,
Thank you for https://github.com/easylist/EasyListHebrew/commit/3eb126d36cd424290a548233498eab06599df68c. 👍

**Comment by Yaron10** [comment]
The problem is there again.
Thank you.

**Comment by EasyListIsrael** [comment]
inn.co.il#@##divTopAd

**Comment by Yaron10** [comment]
@EasyListIsrael,

Thanks for that.
It doesn't work.

FF 51. uBO 1.11.0.

**Comment by Yaron10** [comment]
@IsraeliAdblocker,

The last update has solved it.
Thanks again. I appreciate it.

**
There's now a blank ad at the top of the page.

![image](https://cloud.githubusercontent.com/assets/10229320/22901480/8db72e18-f23a-11e6-9af9-f7c99f49b8cc.png)
