### ISSUE TITLE
Walla New Ads

### ISSUE THREAD

**Issue by DanIbba** [easylist/EasyListHebrew#233]
Same guys like Mako
 
![screen shot 2017-02-12 at 14 07 13](https://cloud.githubusercontent.com/assets/24211092/22861940/21feda44-f12d-11e6-8087-78f35cbbdaea.png)

**Comment by IsraeliUser** [comment]
Please switch to uBlock Origin.

**Comment by DanIbba** [comment]
ads are back with ubo 

https://github.com/uBlockOrigin/uAssets/issues/329
