### ISSUE TITLE
New ads in http://www.inn.co.il/

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#235]
![image](https://cloud.githubusercontent.com/assets/10229320/23104437/9e6b64ae-f6d6-11e6-99b1-47d0f37ebd1c.png)

Thank you.

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/6e5df54231bec563ca8b512dfde5218cff0d0acd

**Comment by Yaron10** [comment]
@IsraeliAdblocker,

Thank you. I appreciate it.

There's still a blank add at the top.

![image](https://cloud.githubusercontent.com/assets/10229320/23188085/0945fc4c-f896-11e6-916f-a0f06ba61d88.png)

**Comment by IsraeliAdblocker** [comment]
Hidding divTopAd would trigger their anti-Adblock on videos.

**Comment by Yaron10** [comment]
So I understand nothing else can be done, is that correct?

Thank you.
