### ISSUE TITLE
Ads in sport5.co.il

### ISSUE THREAD

**Issue by hoofnmouthartist** [easylist/EasyListHebrew#237]
coming from the following domain:
sporty.gdn

**Comment by IsraeliAdblocker** [comment]
can't see any, please share screenshot and please use Ublock + Hebrewlist

**Comment by idan-hartzvi** [comment]
Now the ads are back

**Comment by IsraeliAdblocker** [comment]
Can't reproduce, are you sure you are using the most updated version of the HebrewList? can you share a screenshot with open console/FF report?

**Comment by idan-hartzvi** [comment]
Now the images on the articles are gone
http://www.sport5.co.il/articles.aspx?FolderID=274&docID=238234&lang=HE

http://imgur.com/a/FF1A3

**Comment by idan-hartzvi** [comment]
And now the video also gone :(
http://playbyplay.sport5.co.il/?GameID=91716&FLNum=25

http://imgur.com/a/cZNsW

**Comment by idan-hartzvi** [comment]
Any update??? Are you ever going to fix it???

http://www.sport5.co.il/articles.aspx?FolderID=64&docID=238617&lang=HE
http://imgur.com/a/gMkEa

**Comment by idan-hartzvi** [comment]
And???

**Comment by IsraeliAdblocker** [comment]
currently the website is blocking the images when it recognizing Adblock, I'm trying to find the right filter to whitelist in order to disable this message, if you have a good suggestion, please share.

**Comment by ghajini** [comment]
@gorhill probably can have idea, how to fix this?
