### ISSUE TITLE
Mako.com Ads

### ISSUE THREAD

**Issue by YoYo06** [easylist/EasyListHebrew#239]
Hello,

In the inner pages at Mako there are sssooo many ads (see atached). I use ABP on Chrome

![capture](https://cloud.githubusercontent.com/assets/22640964/23567366/a55b8e7e-005e-11e7-8149-bb5803bc8c6d.JPG)

**Comment by IsraeliAdblocker** [comment]
please use Ublock + Hebrewlist, ABP is working on a fix.

**Comment by YoYo06** [comment]
Hi
Tried Ublock and there are still ads....Now back to ABP and its even worse...there are commercials in videos :(

**Comment by IsraeliAdblocker** [comment]
Just checked both FF and Chrome with Ublock origin, no ads at all.
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

**Comment by amosdabu** [comment]
just switch to Ublock origin and  mako work very good no ads 
pass the adblock bloker in mokotv   
thanks  for the god work
