### ISSUE TITLE
False positive in rotter.net/name

### ISSUE THREAD

**Issue by eran-** [easylist/EasyListHebrew#240]
The following regexes are causing false positives in rotter.net/name:
- `||rotter.net^$subdocument `
- `||rotter.name^$subdocument `

It causes the following frames to be dropped, which are clearly not advertisement, and are not harming usability, but the other way around:

- http://rotter.name/rotter_name_headlines.php
- http://rotter.net/rotter_lastf_news.php

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/63d8119c6956a6e5359969bbc39eae9e93122c83
