### ISSUE TITLE
Ads on Walla

### ISSUE THREAD

**Issue by guyguyguyguy** [easylist/EasyListHebrew#241]
<img width="1056" alt="screen shot 2017-03-15 at 0 58 28" src="https://cloud.githubusercontent.com/assets/11932943/23926008/905fdfb0-091a-11e7-966a-485dda7c50f7.png">

**Comment by guyguyguyguy** [comment]
also inner pages -
<img width="1112" alt="screen shot 2017-03-15 at 1 00 29" src="https://cloud.githubusercontent.com/assets/11932943/23926060/dc7af70e-091a-11e7-89af-486876b5b05e.png">
![Uploading Screen Shot 2017-03-15 at 1.00.20.png…]()

**Comment by IsraeliAdblocker** [comment]
It's an ABP issue, I'll try to add some rules to hide it but it's worthless as of now, ABP is working on a fix. you can try Ublock for now, it is working well enough.
