### ISSUE TITLE
hello , i have a problem with adblock  in ynet 

### ISSUE THREAD

**Issue by fuglo** [easylist/EasyListHebrew#243]
adblock plus  dosen't block for me  ads in ynet , so tried adblock and ublock and they didn't work also 

i tried to scan maleweres by a scanner and i found some and deleted it . but still , ads on ynet !!

i have ADHD and it's very annoying and hard for me to see ads on any web . so pls , help me fix it 

hopefully help :+1: 

thank you

**Comment by YoYo06** [comment]
ME TTOOO

**Comment by YoYo06** [comment]
![1](https://cloud.githubusercontent.com/assets/22640964/24074112/12d9ba36-0c0b-11e7-81bf-21877f378fbd.JPG)

**Comment by IsraeliUser** [comment]
Please switch to **uBlock _Origin_**.

**Comment by fuglo** [comment]
i switch to ublock and it still showes me ads

**Comment by adkiller126** [comment]
uBlock Origin with the Hebrew list?

**Comment by fuglo** [comment]
i don't know how to add hebrew list to ublock . can you tell me how pls ?

**Comment by hmzux** [comment]
Ynet shows ads with uBlock Origin and the most updated ISR: EasyList Hebrew​.
If the ads aren't shown the first time the page loads they will be once the page is refreshed.

**Comment by itayrogg** [comment]
Works fine for me, just update your filters

**Comment by fuglo** [comment]
how to update ???

**Comment by IsraeliUser** [comment]
1. Make sure you're using **uBlock Origin** and not µBlock.
2. Make sure **ISR: EasyList Hebrew** (under **Regions, languages**) is selected.
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters

**Comment by danid12** [comment]
I have this issue too with uBlock Origin in the last days.
the ISR: EasyList Hebrew is updated.

**Comment by danid12** [comment]
I even installed in my Chrome AdBlock and Adblock plus extensions with ISR: EasyList Hebrew list.
it does not help. still the same problem. probably ynet made some changes in their site and the list should be updated.

**Comment by danid12** [comment]
Yesterday ynet.co.il started to work fine again. Don't know what changed.

**Comment by fuglo** [comment]
use חוסם פרסומות ynet

**Comment by yakirbu** [comment]
https://github.com/yakirbu/ynetAdblock

**Comment by kaplandani** [comment]
:-) I can confirm, this is the only one that works https://github.com/yakirbu/ynetAdblock
