### ISSUE TITLE
Yad2 Issue

### ISSUE THREAD

**Issue by raphibb** [easylist/EasyListHebrew#244]
Hi,
In Yad2 car section, there's a banner separating private ads from car agencies ads.
When using EasyList It is also removed but it shouldn't be.
Thanks.
![capture3](https://cloud.githubusercontent.com/assets/10141368/24439093/b00b645c-1454-11e7-8442-f07daf5614fe.PNG)
![capture4](https://cloud.githubusercontent.com/assets/10141368/24439182/4789ae38-1455-11e7-9009-6e44a9a39bf5.PNG)

**Comment by IsraeliUser** [comment]
Fixed: https://github.com/easylist/EasyListHebrew/commit/121a099ff44ba17ba0ad2c115ce0e82147e930fe
