### ISSUE TITLE
ads on ynet or walla

### ISSUE THREAD

**Issue by UserOld** [easylist/EasyListHebrew#245]
Recently adblock plus stopped blocking ads on chrome on the websites ynet.co.il and new.walla.co.il.  I have updated the  filters, and tried other blockers, to no avail. For some reason, it manages to do this on Firefox...

**Comment by IsraeliUser** [comment]
You should move to uBlock Origin.

https://github.com/easylist/EasyListHebrew/issues/243
https://github.com/easylist/EasyListHebrew/issues/233

**Comment by UserOld** [comment]
thanks
 
 
 
-----Original Message-----
