### ISSUE TITLE
video ads on ynet

### ISSUE THREAD

**Issue by guy9322** [easylist/EasyListHebrew#246]
Hi,
I noticed today that there are ads on ynet videos and they are extremely annoying and loud :(
I'm using ublock origin, and it happens on both firefox and google chrome (OS windows 7).

I'd be very happy if you can fix this problem,
Thank you very much,
Guy

**Comment by IsraeliAdblocker** [comment]
Can't reproduce with Ublock.
can you share a screenshot?

**Comment by guy9322** [comment]
screenshot from ynet:
![ynet](https://cloud.githubusercontent.com/assets/26849641/24588726/06c40cec-17d7-11e7-8e13-7ddf0c678851.png)

As you see there is an ad before the video I wanted to see (the ad of the wine)....
As I remember, ublock origin used to block this kind of ads on ynet...

**Comment by fuglo** [comment]
use pls ynet חוסם פרסומות

**Comment by yakirbu** [comment]
https://github.com/yakirbu/ynetAdblock
