### ISSUE TITLE
yad2... previous issue was gone, because someone had disabled all the blocks on the site - ads everywhere, browsing is slow as duck

### ISSUE THREAD

**Issue by PenguinIsrael** [easylist/EasyListHebrew#248]
http://www.yad2.co.il/Yad2/Yad2.php?AreaID=&SalesCatID=6&SalesSubCatID=33&SalesSubCat3ID=0&SaleCondition=0&fromPrice=&untilPrice=&Info=&Order=price&Desc=&Page=2

I've tried blocking manually but some ads are inside the users posts and can't be picked...
So, is it possible to have yad2 without ads again, but not without the search textbox?

Thanks for any help, I'm using this site a lot, and having many tabs of it is too heavy for my fox (firefox)
a fix for my fox? Layla tov

**Comment by IsraeliAdblocker** [comment]
Which Adblock are you using? have you tired ublock Origin yet?

**Comment by PenguinIsrael** [comment]
im using ublock origin. I've blocked items manually, and can't tell if the problem still exist. do you have ads on this site?

**Comment by IsraeliAdblocker** [comment]
which browser? are you sure you are using HebrewList? I've checked now and saw nothing.

**Comment by PenguinIsrael** [comment]
Firefox on Ubuntu, and I'm using ISR: EasyList Hebrew.
Maybe it got fixed, Thanks for the quick help.

**Comment by PenguinIsrael** [comment]
Nope, there are survivors
![2017-04-25 22-28-48](https://cloud.githubusercontent.com/assets/5622266/25403915/a5fc5526-2a06-11e7-9d4b-98c25d81b8c1.png)

This ad still exists. I'm not complaining ofcorse, you made a great job, just letting you know so it would improve.

**Comment by mailnator** [comment]
Hi guys,

They have an object called "DesktopMediaManager". I applied the following filter, and looks like it works good.
`||yad2.co.il##script:contains(DesktopMediaManager)`

This is the first time i'm creating a filter, so it might be not good enough, but I hope it will give you a direction.

**Comment by PenguinIsrael** [comment]
forgot to tell, I dont have this ad anymore too. It might be my manual blocking, but maybe it got fixed too.
Can't tell. Thank for your filter
