### ISSUE TITLE
Ads on Reshet videos

### ISSUE THREAD

**Issue by nikita698** [easylist/EasyListHebrew#250]
Hey,
The Reshet shows have alot of ads and the ad blocker doesn't block them.
every 10 min there are 3 ads which last for 30 seconds each, and it's quite annoying...
can you fix it please? couple of days before the video worked fine without ads.
link: http://reshet.tv/

I'm using ad block plus and google chrome.

**Comment by IsraeliUser** [comment]
Move to uBlock Origin.

**Comment by nikita698** [comment]
what's the difference between adbloack and uBlock?

**Comment by IsraeliAdblocker** [comment]
currently uBlock origin is the only one who can block webRTC requests.

**Comment by nikita698** [comment]
ok, thanks
