### ISSUE TITLE
Ads keep showing

### ISSUE THREAD

**Issue by yoelf22** [easylist/EasyListHebrew#251]
On http://www.globes.co.il

**Comment by IsraeliUser** [comment]
Use uBlock Origin.

**Comment by yoelf22** [comment]
uBlock has it's issues, too + I feel it is burdening my browser. tried, then removed. (Oh, and it doesn't remove all ads, too)

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/901e9c64136dbca7e24fc1999de6dc1cfc0df797
