### ISSUE TITLE
Advertisement on the website walla and Mako

### ISSUE THREAD

**Issue by shlomi284** [easylist/EasyListHebrew#254]
I'm using an extension ublock origin
![image](https://cloud.githubusercontent.com/assets/28808501/26251125/e124fd40-3cb4-11e7-9012-c6caa3a12e9c.png)
![image](https://cloud.githubusercontent.com/assets/28808501/26251136/e9e04804-3cb4-11e7-9647-9d59d32d2282.png)
tnx

**Comment by IsraeliAdblocker** [comment]
can't reproduce, please update your filters and make sure you are running HebrewList.

**Comment by shlomi284** [comment]
All up-to-date
I went adp that Israeli sites circumvented the block ...
Now apparently they bypassed the obstruction of ublobk origin
