### ISSUE TITLE
Lots of ads on mynet

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#256]
Hello,

Could you please add filters to mynet (e.g. http://mynetrishon.co.il/)?

Thank you. I appreciate your work.

***

BTW, http://www.inn.co.il/ needs some maintenance.

**Comment by IsraeliAdblocker** [comment]
solved all mynet websites - https://github.com/easylist/EasyListHebrew/commit/fc444c0b25edec09d7c5681d6012b3ebba3ee802

which ads do you see on inn?

**Comment by Yaron10** [comment]
@IsraeliAdblocker 

> solved all mynet websites - fc444c0

Thank you very much. I appreciate it.
***
As for http://www.inn.co.il/:
The large ad on the main page is quite annoying.
We've discussed that before and I was wondering if something changed and you could possibly block it.

Some other ads show up from time to time on that site.

Best regards.
