### ISSUE TITLE
webrtc Ads at walla.co.il

### ISSUE THREAD

**Issue by hoofnmouthartist** [easylist/EasyListHebrew#259]
Ads served via WebRTC connections on http://walla.co.il/. These seem to be blockable in ABP for Chrome dev build (`$webrtc` as a [new filter option](https://adblockplus.org/development-builds/new-filter-type-option-for-webrtc-connections)). Would you block these in your filter list?

**Comment by IsraeliUser** [comment]
Already in list: https://github.com/easylist/EasyListHebrew/commit/f079f4d312490520b5f7a8d06ddc6bc5dfbda23f

We recommend uBlock Origin.

**Comment by hoofnmouthartist** [comment]
Ah I see. These filters don't work in ABP dev though. In ABP you would need something like `a.zinovila.com^$webrtc,domain=walla.co.il` or `*$webrtc,domain=walla.co.il`

**Comment by hoofnmouthartist** [comment]
Guys, haven't heard from you. Totally understand that you prefer uBlock origin, fair enough. I prefer ABP because of various reasons. Anyways, WebRTC blocking support is in the stable version of ABP for Chrome now. 
Would please give any feedback to my previous message?

**Comment by IsraeliUser** [comment]
Fixed: https://github.com/easylist/EasyListHebrew/commit/0d778a8e4182f84f8040d62ae66b4f09b9b8b0ba

**Comment by hoofnmouthartist** [comment]
Thanks a lot 👍
