### ISSUE TITLE
[finance.themarker.com] Some table data isn't shown correctly

### ISSUE THREAD

**Issue by StentMan** [easylist/EasyListHebrew#260]
Goto: http://finance.themarker.com/bonds and look at the table titled: הרכב מדד אגח כללי ממשלתי
The column titled "שיעור השינוי" is (mostly) empty. Only zeros are shown.
This is because of the following rule:
/themarker\.com\/.{2,36}$/$image,domain=haaretz.co.il|themarker.com 
that blocks these two elements:
http://finance.themarker.com/Images/negative.png
http://finance.themarker.com/Images/positive.png

Adding these fixes the issue:
@@||finance.themarker.com/Images/negative.png$image,domain=finance.themarker.com
@@||finance.themarker.com/Images/positive.png$image,domain=finance.themarker.com
Maybe there's a better solution? I don't know.

**Comment by IsraeliAdblocker** [comment]
https://github.com/easylist/EasyListHebrew/commit/2967fa16097ea64a47f0517984c2135abf0bde54
