### ISSUE TITLE
Nana10: Stop/Pause buttons do not work in videos

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#265]
http://news.nana10.co.il/Article/?ArticleID=1261822&sid=126

Firefox + uBO.

Thank you.

**Comment by EasyListHebrew** [comment]
issue still remains, is it a ublock issue??
https://github.com/gorhill/uBlock/issues/3145

**Comment by EasyListHebrew** [comment]
related to FF56

**Comment by gregoryka** [comment]
Issue continues, using Chrome 68 and uBlock Origin. I have narrowed it down to EasyList's generic filter `/adserver/` blocking `http://lb.advsnx.net/adServer/Service.svc/gnt?...` (rest changes every time) as the cause, and the ublock rule `10tv.nana10.co.il http://lb.advsnx.net/adServer/Service.svc/gnt xmlhttprequest allow` solved the issue for me.
