### ISSUE TITLE
Rimon net filtering

### ISSUE THREAD

**Issue by akak** [easylist/EasyListHebrew#273]
Internet Rimon (or Netspark - it's the same company) has a script for filtering, that slows down the uptime of the site and it's very annoying.
The script is added to every page, and it;s very simple to block it.
I added this rule:
/jsQuilting/*
and it made the job.
even after that I still have my Internet filtered, as I am connected with Rimon, so I don't see any problem to add it to the default list.

**Comment by IsraeliAdblocker** [comment]
I am sorry but HebrewList aren't meant to deal with such situations.
