### ISSUE TITLE
www.inn.co.il: Commercials in Videos 

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#274]
http://www.inn.co.il/News/News.aspx/358914

Thank you.

**Comment by IsraeliUser** [comment]
I can't reproduce.

**Comment by Yaron10** [comment]
I'm using Firefox 52 and uBlockO 1.14.18.

Thank you for looking into it.

**Comment by IsraeliAdblocker** [comment]
fixed.

**Comment by Yaron10** [comment]
👍 
Thank you.
