### ISSUE TITLE
auto.co.il some ads

### ISSUE THREAD

**Issue by cylay** [easylist/EasyListHebrew#277]
using AdNauseam 3.4.402 on Firefox 57
blocked using `##.dynamic-banner`
or blocking `atpclick.com`

<img src="https://screenshots.firefoxusercontent.com/images/3533849f-6eec-4fda-8f1e-608248133b69.jpg">

**Comment by IsraeliAdblocker** [comment]
AdNauseam? I am not fermiliar with this one, Ublock + Hebrew list would work, just checked.
