### ISSUE TITLE
Starting yesterday 28.11.17 there are  ads  at the beginning of Walla's videos

### ISSUE THREAD

**Issue by roni14** [easylist/EasyListHebrew#278]
Starting yesterday 28.11.17 there are  ads  at the beginning of Walla's videos
There are several ads in Walla's videos (https://www.walla.co.il/)
As a result, Firefox (57.0) becomes very slow and can hardly be used
On the other hand uBlock Origin blocks everything 
So everything is normal in Ynet or NRG.

**Comment by IsraeliAdblocker** [comment]
fixed.

**Comment by roni14** [comment]
Unfortunately, ads continue in Walla 
I attach a picture that it exists even now
![10](https://user-images.githubusercontent.com/8658070/33655839-e75c9ec8-da7c-11e7-86d8-d1a3ca95f904.jpg)

**Comment by IsraeliAdblocker** [comment]
Please force update the lists and try again.
