### ISSUE TITLE
problem on themarker.com

### ISSUE THREAD

**Issue by skylas173** [easylist/EasyListHebrew#280]
hello,
when the hebrew language filter-list is enabled, the comments of the articles in www.themarker.com do not appear.

**Comment by IsraeliUser** [comment]
I can't reproduce.
What is your browser and adblocker?

**Comment by skylas173** [comment]
1.14.1042.3 (Official Build) (64-bit) with Adblock 3.22.1

**Comment by IsraeliUser** [comment]
Try uBlock Origin.
