### ISSUE TITLE
AdBlock easy list blocking il.timetoknow.com

### ISSUE THREAD

**Issue by yaacovt2k** [easylist/EasyListHebrew#281]
Hello.
Adblock blocks our Site.

- Our company promotes education through the internet (We are not an advertising company), We work with a lot of schools in Israel with the approval of the Ministry of Education.

- We spend a lot of human resources to help students and Teachers disable Adblock (Phone support) so that they can use our website for multiple purposes (Homework,Classes and Tests). I attached a photo that will help you see what our customers get when they have AdBlok

Chrome Version: 63.0.3239.84
OS: Win 7
Version: 3.22.1

new user in chrome after installing AdBlock:
![beforeeasylistremoved](https://user-images.githubusercontent.com/34742700/34257342-336547de-e662-11e7-9ccb-70f3252ede74.PNG)
after removing the easy list checkbox:
![aftereasylistremoved](https://user-images.githubusercontent.com/34742700/34257412-68952802-e662-11e7-9cad-b4caa98a23e9.PNG)

**Comment by EasyListHebrew** [comment]
@yaacovt2k Hi
i changed something not sure it will fix your issue
if the issue still exists

- check using ublock origin
- attach the full log of the network pane from the chrome developer tools when you load the website (with the issue) pic+txt

**Comment by yaacovt2k** [comment]
1. Opened a new person in chrome and added ublock origin then triel to connect to the website and it didn't block it.
2. Opened a new person in chrome and added ublock origin then triel to connect to the website and it the website got blocked.
<img width="960" alt="network panel pic" src="https://user-images.githubusercontent.com/34742700/34557061-a9d4f01a-f141-11e7-9803-9bd427d0ee29.PNG">

**Comment by IsraeliUser** [comment]
Please try again.

**Comment by yaacovt2k** [comment]
I opened a new user in chrome and installed AdBlock and the issue still exist.

**Comment by IsraeliUser** [comment]
Make sure EasyList Hebrew is enabled.

**Comment by yaacovt2k** [comment]
when EasyList Hebrew is enabled the website is loading.
but i want you to help if you can so that it will work for the student without them having to add the extra filter EasyList Hebrew

I am grateful for your service, and i hope that the solution will help the student in israel study on our website.

**Comment by IsraeliUser** [comment]
@monzta 
Please use this whitelist: https://github.com/easylist/EasyListHebrew/commit/4f3b0fdfbb64a7b7dae09b99346218b82bda29a1

**Comment by yaacovt2k** [comment]
Thank you for your time.
Our developers finally fixed the issue by removing something from the website.
Now our site loads with AdBlock
