### ISSUE TITLE
MAKO's videos seems to not full-screened when EasyList is on

### ISSUE THREAD

**Issue by exx8** [easylist/EasyListHebrew#283]
Hi,
Whenever I watch a video in Mako with your list and I press the full screen button,
the video won't change its size, and instead the rest of the screen turns black.
Is this a known bug? How can I resolve this?

**Comment by IsraeliUser** [comment]
I can't reproduce.
What is your browser and adblocker?
I recommend uBlock Origin.

**Comment by exx8** [comment]
google chrome 63.0.3239.132 
uBlock Origin‬ 1.14.24

**Comment by YoYo06** [comment]
I have the same problem I think....I use uBlock Origin 1.14.24 and Chrome. 
In the last week or so the videos doesn't work. You can hear the sound but the videos doesn't work and the bar in the bottom of the video doesn't show up. 

![untitled](https://user-images.githubusercontent.com/22640964/35484644-4c285d08-045b-11e8-86cd-33f0590ab271.png)

**Comment by exx8** [comment]
Actually it now works fine for me . I keep it open for @YoYo06 .

**Comment by exx8** [comment]
currently seems to work with with nano adblocker and nano defender.
