### ISSUE TITLE
visrtualspirits.com

### ISSUE THREAD

**Issue by YoAm** [easylist/EasyListHebrew#284]
As seen on http://www.shakoof.org.il/%D7%9E%D7%A9%D7%9B%D7%A0%D7%AA%D7%90-%D7%A6%D7%9E%D7%95%D7%93%D7%94-%D7%9C%D7%9E%D7%93%D7%93/

**Comment by IsraeliUser** [comment]
Is it self-promotion?

**Comment by YoAm** [comment]
Yes.

**Comment by IsraeliUser** [comment]
We don't block self-promotion.
