### ISSUE TITLE
mako  require Facebook login to watch video

### ISSUE THREAD

**Issue by yaakovp** [easylist/EasyListHebrew#287]
https://www.mako.co.il/mako-vod-keshet/iron-dome-s1/VOD-3732fb5840a4061006.htm?sCh=b3b8a7c52460f510&pId=957463908

Adblock recommended this:

DIV[id="overlay"]

thanks.

**Comment by IsraeliUser** [comment]
I can't reproduce.
Switch to uBlock Origin.

**Comment by yaakovp** [comment]
on uBlock it better - the overlay isn't visible but the videos isn't clickable

**Comment by IsraeliAdblocker** [comment]
I can't reproduce, tried both ABP and Adblock

**Comment by IsraeliUser** [comment]
I can't reproduce.
Please try again.

**Comment by Yaron10** [comment]
@IsraeliUser,

I'm using Firefox 52 + uBlock Origin firefox-legacy-1.16.4.4.
Can you please test it?

Thank you.

**Comment by IsraeliUser** [comment]
Try Firefox Portable 61/60 ESR + uBlock Origin.

**Comment by Yaron10** [comment]
Thank you.
