### ISSUE TITLE
Multiple ads in https://www.inn.co.il/

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#288]
https://www.inn.co.il/

Could you please have a look?

Thank you.

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/e4f0edd99aa1abf675c5da5746c256cce001cca2

**Comment by Yaron10** [comment]
Thank you. I appreciate your work.

There still are a few blinking ads on various pages.
Here are some from the main page:

![default](https://user-images.githubusercontent.com/10229320/38045920-e9805bfc-32c6-11e8-8e45-fa918d1eb86e.png)

![default](https://user-images.githubusercontent.com/10229320/38045944-fa701f4c-32c6-11e8-8f67-dd6930771342.png)

![default](https://user-images.githubusercontent.com/10229320/38045963-039d3a96-32c7-11e8-8482-ca3e9d19246c.png)

**Comment by Yaron10** [comment]
Many videos start with commercials. Could you please have a look? 
Thanks again. Highly appreciated.

Should I close this issue or keep it open as a reminder for the frequent changes in that site?

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/aaf82e35e066d4750b8705bbe2a79a99c2fb742d

**Comment by Yaron10** [comment]
Thank you.


Still, many videos start with commercials.
https://www.inn.co.il/News/News.aspx/375786

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/0b5ca13c44284da9365a6850aaad4f03b240326c

**Comment by Yaron10** [comment]
@IsraeliUser,

:+1: 
Thank you. I appreciate your work.
