### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [easylist/EasyListHebrew#289]
Anti Adblock. FIxed with `haaretz.com##script:inject(abort-current-inline-script.js,AdBlockUtil)`

**Comment by krystian3w** [comment]
EasyList no use script rules uBlock / Adguard.

Maybe add in a feature sub list with "`#!include`" - [/gorhill/uBlock/releases/tag/1.15.0](/gorhill/uBlock/releases/tag/1.15.0)

**Comment by zaphodbeebblebrox** [comment]
Sorry, I saw an issue in uAssets for it that was closed with a reference to EasyList Hebrew.
