### ISSUE TITLE
Still ad on inn.co.il

### ISSUE THREAD

**Issue by Stagadush** [easylist/EasyListHebrew#293]
URL(s) where the issue occurs

Main site: https://www.inn.co.il/
Video Example - https://www.inn.co.il/News/News.aspx/373930
Describe the issue

Not block ad on site and on video

Screenshot(s)
https://camo.githubusercontent.com/37970cc4589171e9cd022b22d521dd2b364cde67/687474703a2f2f7777772e696e7465726c6f61642e636f2e696c2f75706c6f61642f383834303736382e706e67

Versions

    Browser/version: Firefox 60.0.1
    uBlock Origin version: 16.6

Settings

Not change

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/aaf82e35e066d4750b8705bbe2a79a99c2fb742d
