### ISSUE TITLE
Adblock block

### ISSUE THREAD

**Issue by LoreJon** [easylist/EasyListHebrew#300]
http://www.nifgashim.net/nif/login.csp

![default](https://user-images.githubusercontent.com/16089271/44621551-a32ac600-a8b0-11e8-9ad9-d8e20b6b5bfc.png)

**Comment by EasyListHebrew** [comment]
fixed

**Comment by LoreJon** [comment]
not working for me. thanks

**Comment by LoreJon** [comment]
working now. thanks
