### ISSUE TITLE
Are you serious? $$$$$$

### ISSUE THREAD

**Issue by DanIbba** [easylist/EasyListHebrew#302]
@ryanbr @EasyListIsrael @IsraeliAdblocker @IsraeliUser 

It's funny (actually it's sad) to see you still participate in this FAKE show... Invest your precious time in this lie while the adblockers are selling their users for $$$$$$$$$$. 

I have not been active for a long time, and it's just sickening me... apologize. 

![acceptable ads](https://user-images.githubusercontent.com/24211092/44722869-1f9eee00-aad7-11e8-8448-895292d709a1.png)

**Comment by EasyListHebrew** [comment]
@DanIbba we never tell people to use adblock plus
we are not part of adblock plus
we always tell them to use ublock origin.
if you have nothing positive to say please don't waste out time.
