### ISSUE TITLE
Ynet new Ad Block warning 

### ISSUE THREAD

**Issue by YoYo06** [easylist/EasyListHebrew#303]
Hi

New form today....Ynet asks to remove ad block. I use uBlock Origin and just undated the filters....it didn't help

![image](https://user-images.githubusercontent.com/22640964/45618907-0ce95a80-ba80-11e8-861b-550cbc730b25.png)

**Comment by IsraeliUser** [comment]
I can't reproduce.

**Comment by IsraeliAdblocker** [comment]
Can't reproduce also.
