### ISSUE TITLE
http://koozi.info/

### ISSUE THREAD

**Issue by MrTal** [easylist/EasyListHebrew#304]
Hi
can skip on ad to view in video?:
http://koozi.info/

**Comment by MrTal** [comment]
can you see here:
https://github.com/AdguardTeam/AdguardFilters/issues/26416

this filter help:
[koozi.info#$#.tien-ads-video > div#player { visibility: visible!important; }
koozi.info#$#.tien-ads-video { background: none!important; }](url)

**Comment by IsraeliUser** [comment]
Fixed.
