### ISSUE TITLE
walla.co.il issues

### ISSUE THREAD

**Issue by dorlev2** [easylist/EasyListHebrew#305]
Hi,
I'm using chrome (latest) with adblock plus (latest) (also tried ublock origin).
Since yesterday almost all videos in every article page are stuck for a few seconds 10-20 with a black screen (probably the hidden ad but i can't skip it).
also a lot of articles are broken , for example:
https://sports.walla.co.il/item/3203278
https://food.walla.co.il/recipes
https://vod.walla.co.il/tvshows
https://news.walla.co.il/item/3201760

If you continue to browse the site you will find a lot more.
is that a filter issue? can i disable that specific filter without disabling the entire list?

@EasyListIsrael

**Comment by IsraeliUser** [comment]
Switch to uBlock Origin. Use Firefox to avoid false positives.

**Comment by dorlev2** [comment]
@IsraeliUser  Why should i switch to firefox? i would like to continue using chrome , i can't disable specific filters?

**Comment by MrTal** [comment]
@IsraeliUser 
@dorlev2 
Hi It happened to me, too on chrome, i USE With adgurd
I reported on this A problem here: https://github.com/AdguardTeam/AdguardFilters/issues/26111
and the solution work this add two filter this:
walla.co.il#%#window.atob = function() { };
walla.co.il#%#AG_abortInlineScript(/TextDecoder/, 'atob');
i added this and this work
try too

**Comment by dorlev2** [comment]
@dorlev2 @IsraeliUser @MrTal Ok so the easylist guys took care of that on their side, can you please explain how can i whitelist that specific filter? most of the sports section is broken because of that.

**Comment by IsraeliUser** [comment]
Fixed.

**Comment by MrTal** [comment]
@IsraeliUser 
the ads back...

**Comment by MrTal** [comment]
@IsraeliUser 
now i try and have popup too with Ublock
filter this halpe and solver the a problem in adguard

```
walla.co.il$$script[tag-content="JorLoad"][min-length="50000"][max-length="150000"]
fun.walla.co.il##.game-item > .pre-game
```
2. i found anti adblock more:
in walla games cant see the game with adblock:
https://fun.walla.co.il/game/3205383
with adblock
http://prntscr.com/m1hlzn
without adblock
http://prntscr.com/m1hm8p
the filer this helpd and solver the problem in adguard:
`http://fun.walla.co.il##.game-item > .pre-game
`
(can you see more information here: https://github.com/AdguardTeam/AdguardFilters/issues/27607)
