### ISSUE TITLE
ערוץ הוידאו חסום ב"ישראל היום"

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#310]
https://www.israelhayom.co.il/

![default](https://user-images.githubusercontent.com/10229320/51428782-805ace80-1c10-11e9-8fc7-e5a22848cc0a.png)

.רוב תודות

**Comment by Yaron10** [comment]
Thank you for https://github.com/easylist/EasyListHebrew/commit/7f6319cc4641ce3c9ed7e04c7a91ec44fe2cd727.

Still not working on my machine.
FF 64 + latest uBO.

**Comment by IsraeliUser** [comment]
I can't reproduce.
Please try again and provide a screenshot of uBO's logger.

**Comment by Yaron10** [comment]
It's working now. I don't understand why it didn't yesterday.
Thank you very much. :+1:

**Comment by Yaron10** [comment]
It's not working again.
Could you please have a look?

**Comment by Yaron10** [comment]
:+1: 
Thank you.
