### ISSUE TITLE
yad2 search box is broken

### ISSUE THREAD

**Issue by eaglero18** [easylist/EasyListHebrew#313]
there's an issue with the new redesigned yad2 website
https://user-images.githubusercontent.com/28682096/52912715-c1044100-32bd-11e9-8689-ea660d499a3b.png
The search box is empty / doesn't have any drop lists or text fields

**Comment by EasyListHebrew** [comment]
could not reproduce with ublock on chrome

**Comment by eaglero18** [comment]
Mhm.. weird, it was not working without disabling ublock on firefox or chrome this afternoon.. seems like they temporarily changed something on their site and then reverted it.
