### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by MrTal** [easylist/EasyListHebrew#314]
Hi
have popup in site this: https://sheva7.co.il/
Screenshot: http://prntscr.com/mvh82q

**Comment by MrTal** [comment]
@IsraeliUser

**Comment by IsraeliUser** [comment]
I can't reproduce.

**Comment by MrTal** [comment]
@IsraeliUser 
this very strange It happens too uBlock orgin and also adguard
on google Chrome

**Comment by MrTal** [comment]
@IsraeliUser 
the filter this help:
sheva7.co.il##.maavaron
sheva7.co.il##.advertising-box-wrapp
||sheva7.co.il/wp-content/banners/banner
https://github.com/AdguardTeam/AdguardFilters/issues/31834

**Comment by MrTal** [comment]
@IsraeliUser 
still have popup only with uBlock in Chrome:
http://prntscr.com/nf11kb
http://prntscr.com/nf11mj
http://prntscr.com/nf11q1
with adgurd this work

**Comment by IsraeliAdblocker** [comment]
What about now?

**Comment by MrTal** [comment]
@IsraeliUser 
all click in link have this message::
http://prntscr.com/nhuswi

**Comment by MrTal** [comment]
@IsraeliAdblocker

**Comment by MrTal** [comment]
@IsraeliUser 
@IsraeliAdblocker 
I did some tests and this filter work and no have popup work Chrome and firefox:
`sheva7.co.il##.desktop-display > .maavaron
`
if can you add this please

**Comment by MrTal** [comment]
@IsraeliUser 
now this good tank you
