### ISSUE TITLE
ynet paywall

### ISSUE THREAD

**Issue by shlomiv** [easylist/EasyListHebrew#316]
I got sick of ynet's paywall and made a few of rules to remove most of these entries. I am not too familiar with creating blocking rule, so I hope this helps:

```
##li:has(span:has(img[src^="/images/premium/xsmall_paywall_icon_45x14.png"]))
##div.element:has(span.paywall_art_indicator)
##li:has(a.ynet_pay_54x20)
##li:has(a:has(img.paywall_img_indicator))
##li:has(div:has(div:has(a:has(span.ynet_pay_54x20))))
```

**Comment by IsraeliAdblocker** [comment]
can you send a link to such a paywall page?

**Comment by shlomiv** [comment]
Sure, any page on ynet.co.il. Every page that has that  ![image](https://user-images.githubusercontent.com/379063/56928993-5164bc00-6a8d-11e9-8256-b8ff66677a44.png) in its title is a clickbait to a single paragraph that tries to lure you into paying. 

Here is an example from today, note the second article (in blue):

<img width="671" alt="Screen Shot 2019-04-29 at 2 42 54 PM" src="https://user-images.githubusercontent.com/379063/56929030-70634e00-6a8d-11e9-9b08-2abbf1616ae8.png">

**Comment by IsraeliUser** [comment]
We don't block self-promotion.
Maybe Fanboy's Annoyance List is the right place.

**Comment by shlomiv** [comment]
Oh interesting distinction. Thank you!
