### ISSUE TITLE
https://13tv.co.il - Popup

### ISSUE THREAD

**Issue by MrTal** [easylist/EasyListHebrew#322]
Hi
sometimes have popup in site:
https://13tv.co.il
It happens when click in link on the site:
http://prntscr.com/ngy68r

**Comment by IsraeliUser** [comment]
Do you have any suggestion?
`13tv.co.il##.ad-Unit-Wrp` hides the whole page for a few seconds, so I deliberately removed it.

**Comment by MrTal** [comment]
can't doing this skip automatic?
 like:
http://www.tapuz.co.il/

**Comment by IsraeliAdblocker** [comment]
The only solution that I see is overriding the value of the cookie "r13_maavron"

**Comment by MrTal** [comment]
@IsraeliAdblocker 
i see now this work and no have popup
did you do something?

**Comment by MrTal** [comment]
@IsraeliAdblocker 
@EasyListHebrew 
next check the filter this help and no have popup:
`13news.co.il,13tv.co.il#%#document.cookie = "r13_maavron=5; path=/";

`
https://github.com/AdguardTeam/AdguardFilters/issues/33131#issuecomment-487506357

**Comment by IsraeliUser** [comment]
@mapx- @okiehsch
Is there a solution for uBlock Origin?

**Comment by okiehsch** [comment]
`13tv.co.il##+js(cookie-remover.js, /r13_maavron/)`

**Comment by mapx-** [comment]
maybe
`13news.co.il,13tv.co.il##+js(cookie-remover.js, /r13_maavron/)`

**Comment by MrTal** [comment]
@mapx- 
yes this good now i no see popup also uBlock
@IsraeliUser 
you can addes this filter:
`13news.co.il,13tv.co.il##+js(cookie-remover.js, /r13_maavron/)
`

**Comment by MrTal** [comment]
@IsraeliUser 
now this good tank you
