### ISSUE TITLE
themarker.com does not work on mobile (firefox for android)

### ISSUE THREAD

**Issue by katzelad** [easylist/EasyListHebrew#323]
A blank page is displayed.
Thanks

**Comment by IsraeliUser** [comment]
@mapx- @okiehsch

**Comment by mapx-** [comment]
I cannot reproduce the issue (tested FF builtin emulator, other switcher addons in FF)

**Comment by katzelad** [comment]
The homepage works, try an article:
https://www.themarker.com/career/.premium-1.6220785

**Comment by mapx-** [comment]
fixed
