### ISSUE TITLE
haaretz.co.il

### ISSUE THREAD

**Issue by krystian3w** [easylist/EasyListHebrew#324]
https://old.reddit.com/r/uBlockOrigin/comments/brox4q/trying_to_block_element_with_randomized_id/

**Comment by IsraeliUser** [comment]
Fixed.

**Comment by electric3055** [comment]
This yellow banner reappeared a few days ago, the filters are not working anymore

**Comment by krystian3w** [comment]
I see...

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/41761

**Comment by krystian3w** [comment]
this IMO work:

`haaretz.co.il###__next > div[id] + div[class*=" "] > div[class*=" "]:nth-of-type(2)`

**Comment by electric3055** [comment]
Thanks, it's working

**Comment by krystian3w** [comment]
@IsraeliUser  see https://github.com/AdguardTeam/AdguardFilters/issues/45799

**Comment by IsraeliUser** [comment]
@krystian3w 
Self-promotion, should be added to the Annoyances​​​​​​​​​ list. @mapx- @okiehsch
Make sure it​​​​​ won't trigger their anti-adblock system. See: https://github.com/easylist/EasyListHebrew/commit/1797252b6e85bc3dac586aa2eead1ccec0deab85

**Comment by krystian3w** [comment]
Ad Banner is back: https://old.reddit.com/r/uBlockOrigin/comments/jxl9yz/how_do_i_block_this_random_name_element/

**Comment by IsraeliUser** [comment]
@krystian3w 
Self-promotion, should be added to the Annoyances​​​​​​​​​ list. @mapx-
Make sure it​​​​​ won't trigger their anti-adblock system. Thanks!

**Comment by krystian3w** [comment]
IMO no fixed yet in uBO-Annoyances.

**Comment by mapx-** [comment]
`haaretz.co.il##:xpath(//*[contains(text(),"4.90")]):upward(3)`

**Comment by StentMan** [comment]
This filter: 
`/haaretz\.co\.il\/[\w\.!]+\/[\w\.!]+\/[\w\.!]+\/[\w\.!]+\/[\w\.!]+\//$image,domain=haaretz.co.il|themarker.com`
Seems to be a bit strict. It blocks all the content of: https://www.haaretz.co.il/st/inter/Global/dailyedition/today/
It seems that adding a rule such as this:
`@@||www.haaretz.co.il/st/inter/Global/dailyedition/today/*$image,domain=www.haaretz.co.il`
Fixes it. Probably could tweak this rule a bit, I'm no expert.
