### ISSUE TITLE
Taboola Feed Ads

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#326]
https://www.israelhayom.co.il/article/663741
![תמונה](https://user-images.githubusercontent.com/10229320/59139877-1ebcb600-899f-11e9-9575-5dbd3ef590f3.png)

These annoying new ads are all over (almost in every major site).
Thank you.

**Comment by IsraeliUser** [comment]
I can't reproduce. (Firefox + uBlock Origin)
Try to disable all extensions except uBO.
If it doesn't help please post screenshots of uBO's logger and of _Filter lists_ tab.

**Comment by Yaron10** [comment]
These ads seem to appear intermittently.
I've come across them on ynet and many other sites.
When scrolling down the page, they are "following" and displayed on the right bottom.

Well, I suppose you should encounter them sooner or later.

Thank you.

**Comment by Yaron10** [comment]
Can you please try the following link?
https://www.inn.co.il/News/News.aspx/404345

![תמונה](https://user-images.githubusercontent.com/10229320/59311730-410e4680-8cb3-11e9-9378-7088e5b2b3bf.png)

**Comment by IsraeliUser** [comment]
I can't reproduce.
Please provide additional information: browser/adblocker/OS - specify versions.
Add screenshots of your _Filter lists_ menu (list of your filter lists / subscriptions) and of your browser's extensions menu.

**Comment by Yaron10** [comment]
It's tricky. Now the ad does not appear in that page.

Windows 7 32-bit.
Firefox 67.0.1.
uBlock Origin 1.19.6.

![תמונה](https://user-images.githubusercontent.com/10229320/59354317-95560c80-8d2d-11e9-919d-378fd5c0d8c9.png)

It happens regardless of any other extensions.

**Comment by IsraeliUser** [comment]
You disabled some of the default filter lists.
On the _Settings_ menu please click on _Reset to default settings..._

**Comment by Yaron10** [comment]
I usually don't need all those lists but I'll try it.

I appreciate your help.

**Comment by IsraeliUser** [comment]
@ryanbr
FYI

**Comment by Yaron10** [comment]
Thank you.

**Comment by Yaron10** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=43209
