### ISSUE TITLE
A blank page on https://www.bhol.co.il

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#327]
https://www.bhol.co.il/news/1009641
A blank page appears for a few seconds before moving to the content.

Thank you.

**Comment by IsraeliUser** [comment]
@mapx- @okiehsch

**Comment by okiehsch** [comment]
I can't reprodcue a blank page.

**Comment by Yaron10** [comment]
I can't reproduce it either now.

Thank you @IsraeliUser and @okiehsch.

**Comment by Yaron10** [comment]
Can you try it again please?
Thanks.

**Comment by okiehsch** [comment]
`bhol.co.il##.fade`

**Comment by Yaron10** [comment]
:+1: 

Is it possible to make the scroll-bars appear without a delay?

Thank you.

**Comment by okiehsch** [comment]
> Is it possible to make the scroll-bars appear without a delay?

`bhol.co.il##body:style(overflow: auto !important;)`

**Comment by Yaron10** [comment]
Great.

Thank you.
