### ISSUE TITLE
Haaretz detects ublock and redirects paywalled artciles to https://www.haaretz.co.il/hblocked

### ISSUE THREAD

**Issue by tworepetae** [easylist/EasyListHebrew#328]
Worked fined a couple of days ago but now it redirects premium artciles to https://www.haaretz.co.il/hblocked. Using latest Firefox on Windows 10.
Not sure if it's an EasyListHebrew issue, so apologies if I'm in the wrong place.

**Comment by IsraeliUser** [comment]
@okiehsch @mapx-

**Comment by okiehsch** [comment]
Your filter
`haaretz.co.il##div[class*="addBlocker"]`
is triggering the redirect.
Removing it fixes the issue on my end.

**Comment by IsraeliUser** [comment]
@okiehsch 
Thanks!

**Comment by tworepetae** [comment]
Fixed this on my end as well, thank you.

**Comment by tworepetae** [comment]
Started happening again...

**Comment by mapx-** [comment]
`haaretz.co.il#@#.js-dfp-ad`

**Comment by IsraeliUser** [comment]
@mapx- 
Thanks!

**Comment by tworepetae** [comment]
And yet again...

**Comment by mapx-** [comment]
test
```
haaretz.co.il#@#div[class*="banner"]
haaretz.co.il#@#[data-back="promotional-content"]

haaretz.co.il##div[class*="banner"]:style(height: 10px !important)
haaretz.co.il##[data-back="promotional-content"]:style(height: 10px !important)
```

**Comment by mapx-** [comment]
another test (without the filters above)
`haaretz.co.il##+js(aeld, , clientHeight)`

**Comment by tworepetae** [comment]
> 
> 
> another test (without the filters above)
> `haaretz.co.il##+js(aeld, , clientHeight)`

seems to be working, thanks! (again)

**Comment by IsraeliUser** [comment]
@mapx- 
Thanks!
