### ISSUE TITLE
https://www.shvoong.co.il/%d7%94%d7%90%d7%9d-%d7%a8%d7%9b%d7%99%d7%91%d7%94-%d7%99%d7%a2%d7%99%d7%9c%d7%94-%d7%99%d7%95%d7%aa%d7%a8-%d7%9e%d7%a8%d7%99%d7%a6%d7%94-%d7%9c%d7%a6%d7%95%d7%a8%d7%9a-%d7%99%d7%a8%d7%99%d7%93%d7%94/123870/

### ISSUE THREAD

**Issue by roy651** [easylist/EasyListHebrew#329]
Side panels not blocked and can't be blocked using manual block

**Comment by IsraeliUser** [comment]
I can't reproduce.

**Comment by roy651** [comment]
@IsraeliUser they recently removed the ad on the side panels - so the issue cannot be reproduced now. I'll reopen and ping you if they load it back up again. Thanks!
