### ISSUE TITLE
School logo Blocked in leyada.net

### ISSUE THREAD

**Issue by mile-ne** [easylist/EasyListHebrew#330]
### **List the website(s) you're having issues:**

https://leyada.net

### **What happens?**

**Content is blocked by a generic filter**

### **List Subscriptions you're using:**

Easylist+ABP filters

### **Your settings**

Chrome 77

### **Other details:**

![NB5SyoiPMV](https://user-images.githubusercontent.com/33632092/66379518-d72e5100-e9b5-11e9-892a-71c4d27b455e.jpg)

Let me know if you prefer me to send over to Easylist
Thanks

**Comment by IsraeliUser** [comment]
Fixed.
