### ISSUE TITLE
Sport5 Games Results blocked

### ISSUE THREAD

**Issue by Idan-1337** [easylist/EasyListHebrew#333]
The issue is with the blocking rule:
/^(?![a-zA-Z0-9\-]+\:\/+([^\/\:\.]+\.)*((gov|idf|muni|ac|k12|net)\.il|(google|blogspot|phpbb|minifier|enable|nagich|nagishplus|nagishly|livedns|23tv|glz|icast|ecast|mediacast|live1|siz|gif|meduzot|livegames|2net|weather2day|mekorotapp|e-vrit|fav|slash|rabbi|icdn|mako|auto|globes|dominos|linicom)\.co\.il|(kan|makan|oref|parks|imj|nli|bh|isoc|hebrew-academy|kineret|teva|zavit|profile)\.org\.il)\.?([\/\:]|$))^[a-zA-Z0-9\-]+\:\/+[^\/\:]+\.il\.?([\/\:]|$)/$3p,domain=sport5.co.il

This rule not included the domain:
www.telesport.co.il

That serving the games results.
Please add it to this rule, or better, disable this rule completely.
I can't see any new ads when the rule is disabled, probably it's left over from old times.

I can make PR if you want.

**Comment by IsraeliUser** [comment]
Fixed.
