### ISSUE TITLE
Commercials in https://www.ch10.co.il 

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#334]
https://www.ch10.co.il/news/563240/#.XhZXfM5S_R0

Thank you.

**Comment by IsraeliUser** [comment]
Fixed in uBlock Origin.

**Comment by Yaron10** [comment]
Fixed in the link above.
But commercials are still played in many other pages on that site.

https://www.ch10.co.il/news/564843/#.XiBYnc5S_R0

![תמונה](https://user-images.githubusercontent.com/10229320/72526053-37167c80-386e-11ea-89d9-5f5c4666d67c.png)

https://www.ch10.co.il/news/565033/#.XiBY785S_R0

![תמונה](https://user-images.githubusercontent.com/10229320/72526112-58776880-386e-11ea-9590-6c3c12f200b2.png)

Thank you.

**Comment by IsraeliUser** [comment]
Fixed.

**Comment by Yaron10** [comment]
:+1: 
Great. Thank you.
