### ISSUE TITLE
Blacklist removal of an academic interactive tool for COVID-19 outbreak detection

### ISSUE THREAD

**Issue by gilcaspi** [easylist/EasyListHebrew#339]
Hi,
We have an academic interactive tool for COVID-19 outbreak detection that is being used by policymakers and researchers all around the world.
To our dismay, we found out that some of our users are having issues using this tool due to this automatic addition of our domain to your blacklist.
Can you please make sure that our domain is excluded from your blacklist?
In addition, we would like to understand which rule made us in. 

The domain:
covid19maps.org
https://www.covid19maps.org

Best regards,
Gil Caspi
gilcaspi@gmail.com
on behalf of COVID-19 Research Team

**Comment by IsraeliUser** [comment]
Your domain is **not** in our blacklist. In fact it's in our whitelist for some websites...
I need more details - browser, adblocker and filter lists.
Can you reproduce? Try to use your adblocker's logger and see what filter causes the issues.
