### ISSUE TITLE
globals anti-adblock and banner

### ISSUE THREAD

**Issue by naftali100** [easylist/EasyListHebrew#341]
adlock.com###banner_full
apeare when scroling to the page end

globes.co.il###overlayAdb
globes.co.il###pianoBottomBanner

**Comment by IsraeliUser** [comment]
I can't reproduce.
What is your browser and adblocker?
We recommend uBlock Origin.

**Comment by naftali100** [comment]
> I can't reproduce.
> What is your browser and adblocker?
> We recommend uBlock Origin.

I'm using adblock plus with this list

**Comment by IsraeliUser** [comment]
Try switching to uBlock Origin and make sure EasyList Hebrew is enabled.

**Comment by naftali100** [comment]
you right. I switched and really did not exist. interesting...

**Comment by naftali100** [comment]
adlock.com###banner_full
still exist even with ubo

**Comment by IsraeliUser** [comment]
@naftali100 
Go to the extensions page and make sure all adblockers, except uBlock Origin, are removed / disabled.
