### ISSUE TITLE
Ads on walla

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#343]
https://news.walla.co.il/item/3383141

![תמונה](https://user-images.githubusercontent.com/10229320/91505236-c7727080-e8d7-11ea-8f3b-625107f34c5c.png)

Thank you.

**Comment by nomaed** [comment]
Don't know whether it's something they added but looks like Element Zapper is also misbehaving. After several zaps, it stops working (no overlay or any activity on mouse hovering elements).

I don't know if it's related though.

**Comment by nomaed** [comment]
I'm using uBlock Origin and see a bunch of errors in the console.

@Yaron10 what plugin are you using?

![image](https://user-images.githubusercontent.com/9551921/91535845-73d64600-e91c-11ea-83fd-d18413f3f470.png)

**Comment by Yaron10** [comment]
@nomaed,

I'm using Firefox + uBlock Origin.

Just tried that page again and the ads are gone. Go figure.

**Comment by nomaed** [comment]
I tried with both Firefox now, and Chrome, latest uBlock Origin + updated EasyList Hebrew, and on both I see ads.

First time I opened sports.walla.co.il in Firefox there were no ads, but after reloading the page they appeared :\

**Comment by nomaed** [comment]
Tried with AdBlock Plus, and it's the same result. I suppose that the devs at Walla are working hard to overcome blockers :\

**Comment by Yaron10** [comment]
@nomaed,

> First time I opened sports.walla.co.il in Firefox there were no ads, but after reloading the page they appeared

Updating the list and clearing the cache seems to have solved the problem.

@IsraeliUser,

Thank you. :+1:

**Comment by propellerz** [comment]
Looks like they implemented a new way to fight adblockers, seems to be related to possibly feeding it via javascript and/or from the main host of the website. Site first loads ad-free for a few seconds and then the 'thing' is being activated and the ads come up (they are blocked if you actually try to click them and open them, but they still appear all over the page).

There even seems to be some random encryption-like codes the are automatically generated in the source. Plus a taunt from the team when trying to locate.

Examples that show ads at the time of writing this message:
Main page - https://www.walla.co.il/
Random article - https://news.walla.co.il/item/3390855
(Try refreshing if ads don't show in a few seconds)

Also there appears to be a 'taunt' message from the team in the HTML source that's been added along with this new method:

```
> <!DOCTYPE html>
> --
>   | <!--
>   | Perfection is achieved,
>   | not when there is nothing more to add,
>   | but when there is nothing left to take away
>   |  
>   | Walla R&D 2020
>   | -->
```

**Comment by propellerz** [comment]
UPDATE: Just for fun, I upgraded both my uBlock Origin and uMatrix to the developer version, so uBO is v1.4.1b0 instead of stable 1.30.0. Using the same settings and lists as with the original version, this appears to successfully block the ads (and restore picker/zapper mode functionality for the site).
