### ISSUE TITLE
Hosts file version?

### ISSUE THREAD

**Issue by sl4vkek** [easylist/EasyListHebrew#345]
Is it possible to convert this to a [hosts file](https://en.wikipedia.org/wiki/Hosts_(file)) version?
It would make it easier to integrate with [Pi-Hole](https://pi-hole.net/)

**Comment by sl4vkek** [comment]
Wrote a script: https://gist.github.com/sl4vkek/20bfb4ead2e36bb71f8545e030ab20d4
Please add this by default

**Comment by IsraeliUser** [comment]
You should adjust your script a bit: look only for filters that start with `||` and don't contain any `/`'s or `:`'s.
(`||example.com/abc^`, `||example.com:` and `@@||example.com^` should not be converted)
Make a pull request (`create.bat` and `create.sh` should be changed too), check if everything works fine, and I will merge it.
