### ISSUE TITLE
וידאו באתר רשת לא עובדים

### ISSUE THREAD

**Issue by shlomi284** [easylist/EasyListHebrew#346]
https://13tv.co.il/item/mood/the-amazing-race/season-08/clips/xcuzl-2060589/?utm_source=MAIN&utm_medium=super_pic
לא נטען

**Comment by IsraeliUser** [comment]
I can't reproduce.
Make sure EasyList Hebrew is enabled. Use uBlock Origin.

@mapx-
Can you reproduce?
Thanks!

**Comment by mapx-** [comment]
No issue on my side, all videos are playable

**Comment by IsraeliUser** [comment]
@mapx- 
Thanks for your comment.

**Comment by aaroncox31** [comment]
I also have this issue on some videos.
Example: 
https://13tv.co.il/item/mood/the-amazing-race/season-08/episodes/wjqep-2061778/?utm_source=MAIN&utm_medium=super_pic
The link @shlomi284 posted does work (uBlock origin+EasyList Hebrew on chrome)
