### ISSUE TITLE
Haaretz filter removal request

### ISSUE THREAD

**Issue by chenaviv** [easylist/EasyListHebrew#348]
Hi,

This is in regards to the next JS filter:
https://github.com/easylist/EasyListHebrew/blob/d0b055672e4d4487859f57dfbcfd817aa27f0586/EasyListHebrew-uBO.txt#L95

The `uBO.txt` file includes a very general filter that blocks all attempts of adding listeners to the scroll event.

This has caused some serious, non ad-related bugs in the site, e.g. site navigation header disappears and disabled completely in article pages (currently resolved, but in a temporary, non-ideal manner).

The addition of this filter dates back to issue #324, which refers to the bottom strip on the homepage. The scroll event listeners seem to have been blocked due to a flickering issue. I believe the flickering has since been resolved on our end, and in my testing, there has been no flickering even with this filter disabled.

With that in mind, would it be possible to reconsider this filter altogether?

On a slightly different issue, it would also be appreciated if the following filter, related to issue #328, had a more target specific filtering expression, as `clientHeight` is quite common, which means this could easily break other pieces of code, most specifically in special, interactive articles.
https://github.com/easylist/EasyListHebrew/blob/d0b055672e4d4487859f57dfbcfd817aa27f0586/EasyListHebrew-uBO.txt#L96

Chen Aviv,
Haaretz

**Comment by IsraeliUser** [comment]
@mapx-
How can I make the second filter more specific?
Thanks!

**Comment by mapx-** [comment]
`addEventListener("load", function(){var n=e.readQuery({query:j}).user.type;n&&"paying"!==n&&t.ref&&t.ref.clientHeight<=0&&(window.document.location.href="/hblocked?returnTo=".concat(encodeURIComponent(window.document.location.href)))})`

well, 

`haaretz.co.il##+js(aeld, , document.location.href)`
or
`haaretz.co.il##+js(aeld, , hblocked)`
or
`haaretz.co.il##+js(aeld, , clientHeight<=)`

**Comment by chenaviv** [comment]
@IsraeliUser Thanks :)

**Comment by chenaviv** [comment]
Thanks again!

**Comment by krystian3w** [comment]
Maybe sticky, baner visible again.
