### ISSUE TITLE
Ads on Walla

### ISSUE THREAD

**Issue by 007me** [easylist/EasyListHebrew#349]
Hi,
It seems that there's no solutions to the Ads on walla.co.il for a long time now.
Any solution please?

**Comment by IsraeliUser** [comment]
browser / adblocker ?

Please switch to uBlock Origin and make sure EasyList Hebrew is enabled.

**Comment by 007me** [comment]
Hi, what is uBlock?

**Comment by IsraeliUser** [comment]
https://github.com/gorhill/uBlock#ublock-origin
https://github.com/gorhill/uBlock#installation
https://github.com/gorhill/uBlock#note-for-all-browsers
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists

**Comment by krystian3w** [comment]
Race condition:

https://old.reddit.com/r/uBlockOrigin/comments/kjyo6k/ubo_is_acting_strangely_in_a_specific_website/

consider use html filtering for Firefox:

```
walla.co.il##^script:has-text(200===)
```
