### ISSUE TITLE
Add Easylist to Chrome without installing extension

### ISSUE THREAD

**Issue by asher0pa** [easylist/EasyListHebrew#352]
Hi,

kind of general question sorry if it's not directly relevant.

I want to implement EasyList for chrome without installing any extension, is it possible?

TNX

**Comment by IsraeliUser** [comment]
You should ask Chrome developers.
We highly recommend uBlock Origin.
Android users can use uBlock Origin on Firefox.

**Comment by EasyListHebrew** [comment]
perhaps you can use brave browser
