### ISSUE TITLE
עמודים תחת האתר של וואלה הופכים לעמוד ריק כשהטעינה מסתיימת

### ISSUE THREAD

**Issue by bugsy45** [easylist/EasyListHebrew#356]
תוך כדי הטעינה רואים את העמוד אך ברגע שהיא מסתיימת הוא הופך לריק.
לאחר נטרול של EasyList Hebrew הבעיה נעלמת

אני משתמש ב- uBlock Origin

**Comment by glekner** [comment]
same for me

**Comment by IsraeliUser** [comment]
`walla.co.il`
blank page after loading, Chrome + uBO + EasyList Hebrew

@mapx-
What do you suggest?
thanks!

**Comment by mapx-** [comment]
remove & retest

```
walla.co.il##+js(abort-on-stack-trace, Math.random, /computed|blob/)
walla.co.il##+js(abort-on-stack-trace, Object, injectedScript)
```
