### ISSUE TITLE
mako.co.il

### ISSUE THREAD

**Issue by talregev** [easylist/EasyListHebrew#358]
Please remove empty style tag inside head tag. In dark mode, it cause the website to flash. 
```html
<head>
.....
<style></style>
....
</head>
```

I don't know how to write a rule for it.
If you don't want to remove it, please help me to write a custom rule that I can remove it locally. thank you.

**Comment by IsraeliUser** [comment]
@mapx-
What do you suggest?

**Comment by mapx-** [comment]
I see no empty style tag, more info ?

**Comment by talregev** [comment]
I found my problem. I am using dark mode, and every time the weather in the top of the website is switching, is load all the page and make the page flash. (going from white to my dark mode). 
So I block in my adBlock the weather from mako. but this change is not good for all, so don't do it. I will close this issue.
