### ISSUE TITLE
bhol.co.il

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#359]
https://www.bhol.co.il/news/1183422

![תמונה](https://user-images.githubusercontent.com/10229320/107418102-efb8f900-6b1e-11eb-9aa0-9ffcb2abc24d.png)

***
https://www.bhol.co.il/news/1183431

![תמונה](https://user-images.githubusercontent.com/10229320/107418191-095a4080-6b1f-11eb-9242-a3a7862d59f2.png)
***

Firefox 85 + latest uBO.

Thank you.

**Comment by IsraeliUser** [comment]
I can't reproduce.

**Comment by Yaron10** [comment]
I've just reproduced both with Firefox 85 + latest uBO (default settings).
**Please clear the site cookies before testing.**
***
https://www.bhol.co.il/news/1183422

![תמונה](https://user-images.githubusercontent.com/10229320/107875188-1ed8bd00-6ec7-11eb-9935-8d33d1c67359.png)

***
https://www.bhol.co.il/news/1183431

![תמונה](https://user-images.githubusercontent.com/10229320/107875225-4af43e00-6ec7-11eb-8542-822daf0e8a36.png)

**Wait some 5 seconds and you'll get the second ad.**
![תמונה](https://user-images.githubusercontent.com/10229320/107875249-770fbf00-6ec7-11eb-9198-7874aaaeb795.png)
***
And another one on the main page:
https://www.bhol.co.il/

![תמונה](https://user-images.githubusercontent.com/10229320/107875305-de2d7380-6ec7-11eb-93bc-cf22946e2ef9.png)

Thank you. I appreciate it.

**Comment by Yaron10** [comment]
@IsraeliUser,

Thank you. :+1: 

There's also an old floater (please clear cookies and wait a few seconds).
https://www.bhol.co.il/news/1183422

![תמונה](https://user-images.githubusercontent.com/10229320/108053148-b5d37f80-7055-11eb-960a-eab8c627eb38.png)

***
And a new one on the main page:
https://www.bhol.co.il/

![תמונה](https://user-images.githubusercontent.com/10229320/108053275-de5b7980-7055-11eb-9b1b-5f7ef988007a.png)
