### ISSUE TITLE
morfix.co.il

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#360]
https://www.morfix.co.il/hello

Wait a few seconds.

![תמונה](https://user-images.githubusercontent.com/10229320/110254364-90bc9780-7f97-11eb-9cb6-3ce8907e364c.png)

Thank you.

**Comment by Yaron10** [comment]
@IsraeliUser,

:+1: 
Thank you.

**Comment by Yaron10** [comment]
It's back there.

Thank you.

**Comment by Yaron10** [comment]
@EasyListHebrew,

Could you please have a look?

Thank you.

**Comment by Yaron10** [comment]
I'm using Firefox + uBlock.
Clear cookies or try in a private window, and _wait a few seconds_.

**Comment by Branzeturi** [comment]
`morfix.co.il##.top_line_ad_translation` for space

Hi, @Yaron10! If you still use Firefox, do you use Firefox's Tracking Protection?

**Comment by Yaron10** [comment]
@Branzeturi,

Thanks for replying.

I've disabled Firefox's Tracking Protection.

Just updated the lists. The issue still exists.

**Comment by Branzeturi** [comment]
You're welcome! Are you using uBlock Origin? And, do you have more than one ad blocker?

**Comment by Yaron10** [comment]
@Branzeturi,

I'm using only uBlock Origin.

> Did you try enabling EasyPrivacy?

👍 

`EasyPrivacy` blocks that popup.
I wonder which rule there does it.

Thanks again.

*** 
STR without EasyPrivacy:
Clear cookies or try in a private window.
https://www.morfix.co.il/Issue
Close that tab.
Re-open it and wait a few seconds.

**Comment by Branzeturi** [comment]
The `EasyPrivacy` filter list contains `! Admiral` two times

**Comment by Yaron10** [comment]
What's the point of having the same rule twice?

Adding `! Admiral` to My Filters does not block that popup.

Can you reproduce it without `EasyPrivacy`?

**Comment by Branzeturi** [comment]
I meant that there are "comments" which suggest a section for `'Admiral'` things I think.

And I didn't reproduce anti-adb on the given URL without `EasyPrivacy`, with or without `EasyList Hebrew` -- however I did encounter without having `EasyPrivacy`, PGL's included-in-uBO list and `EasyList Hebrew` enabled locally

**Comment by Yaron10** [comment]
Thank you for testing. I appreciate it.

**Comment by Branzeturi** [comment]
You're welcome

**Comment by Hebrew-uBO-User** [comment]
I can't reproduce.

@Yaron10 
Create a new Firefox profile.

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

Reproducible in a new profile.

**Clear cookies.**
https://www.morfix.co.il/hello
Close that tab.
https://www.morfix.co.il/Hi
Wait until you get:

![תמונה](https://user-images.githubusercontent.com/10229320/177842924-39334d1f-7ab1-4fcc-bbdb-2e97c846a911.png)

Close that tab.
https://www.morfix.co.il/של
Wait until you get:

![תמונה](https://user-images.githubusercontent.com/10229320/177843379-1f550804-8d6e-4c03-94f5-a0a21441946d.png)

Thank you.

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 
I need more info.
Please create a report using uBlock Origin.
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools

**Comment by mapx-** [comment]
@Yaron10 I cannot reproduce your issue. IS it about anti-adblocking ? (I don't read hebrew lang)

Follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Yaron10** [comment]
@mapx-,

Thank you for your help here too. I appreciate it.

> IS it about anti-adblocking ?

Yes, it is.

> Follow all these indications:

As I've mentioned in https://github.com/easylist/EasyListHebrew/issues/360#issuecomment-1140338815, EasyPrivacy does block that popup.

But I wouldn't like to enable that list just for one rule. And I'm wondering which rule there does it.

My enabled lists are:
uBlock Filters.
EasyList.
EasyList Hebrew.

**Comment by mapx-** [comment]
You should use EP => is blocking a lot of admiral domains

However, add and test one by one (the first one si blocking that domain from EP)

```
`||warmafterthought.com^`
morfix.co.il##^script:has-text(admiral)
```

@Hebrew-uBO-User I guess you could add the second filter for firefox

**Comment by Yaron10** [comment]
@mapx-,

👍 
Great!

I'm using Firefox and `morfix.co.il##^script:has-text(admiral)` blocks those popups.

Thanks again for your time.

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 
Please use the default setup.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists

@mapx- 
Thank you!

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

👍 
Thank you.

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

That popup is displayed again.
Could you please have a look?

Thank you.

**Comment by Yaron10** [comment]
@mapx-,

The rule `morfix.co.il##^script:has-text(admiral)` no longer blocks that popup.
I'd appreciate your help.

**Comment by mapx-** [comment]
The filter still remove this inline script (in firefox)

```
<script>
        window.admiral = window.admiral || function () { (admiral.q = admiral.q || []).push(arguments) };
        window.admiral("targeting", "set", "UserType", "Non Registered");
    </script>
```

**Comment by Yaron10** [comment]
@mapx-,

Thank you for replying. 👍 

I'm using Firefox.
That filter used to work and block the popup.
But in the past few days it's displayed again.

Any idea?

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 
I can't reproduce.
(Chromium / Firefox + uBlock Origin)
Please test with the default settings.

**Comment by Yaron10** [comment]
As I've mentioned in https://github.com/easylist/EasyListHebrew/issues/360#issuecomment-1140338815, EasyPrivacy does block that popup.

But I wouldn't like to enable that list just for one rule. And I'm wondering which rule there does it.

My enabled lists are:
uBlock Filters.
EasyList.
EasyList Hebrew.

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 
There is no reason not to enable the default filter lists.
It won't slow down your browser. In fact, it can even help to speed up page loading times.

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

I'm not sure this is the correct approach, but I respect your opinion.
Thank you.

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 

Test
`||hsforms.com^*/counters.gif$domain=morfix.co.il`
`||mcdp-*.outbrain.com^$domain=morfix.co.il`

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

Those rules do NOT block the popup.
Thank you.

**Comment by mapx-** [comment]
maybe you disable Peter Lowe's list too

test

`morfix.co.il##+js(aopr, googletag)`

or 

`||warmafterthought.com^`

**Comment by Yaron10** [comment]
@mapx-,

`||warmafterthought.com^` does block it.
Thank you.
