### ISSUE TITLE
Adds on Youtube

### ISSUE THREAD

**Issue by Daniel1158** [easylist/EasyListHebrew#369]
I'm with google chrome. Adblock is my only extension. And There are adds on youtube before the video starts. (this is a PC). sometimes even 2 ads. Please help me.
(Not on Saturday please).

</div></div></div>

**Comment by Daniel1158** [comment]
Not on Saturday please.

**Comment by IsraeliUser** [comment]
Switch to uBlock Origin.

**Comment by Daniel1158** [comment]
> Switch to uBlock Origin.

Thanks but i'm used to Adblock. Is it possible to use both?

**Comment by IsraeliUser** [comment]
We recommend uBlock Origin.
You can import your own custom filters from Adblock to uBlock Origin.

> Thanks but i'm used to Adblock. Is it possible to use both?

It's not recommended: https://github.com/gorhill/uBlock#note-for-all-browsers
