### ISSUE TITLE
https://ch10.co.il

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#371]
https://ch10.co.il/news/681230/#.YO8GIEBRU_5

![תמונה](https://user-images.githubusercontent.com/10229320/125651744-75b65594-dec8-43ad-ae81-4ecdd23c1804.png)

Playing that video, a commercial is run and later `https://corona.health.gov.il/` opens.

Thank you.

**Comment by Yaron10** [comment]
👍 
Thank you. I appreciate it.

**Comment by Yaron10** [comment]
https://ch10.co.il/news/682634/#.YPsHt0BRU_4

Thank you.

**Comment by Yaron10** [comment]
https://ch10.co.il/news/807124/#.ZA76Ax9Bw_5

Could you please have a look again?

Thank you.

**Comment by Yaron10** [comment]
@mapx-,

All the videos in that site start with a commercial.
I'd appreciate your help.

**Comment by mapx-** [comment]
Test

`*.mp4$media,1p,redirect=noopmp3-0.1s,domain=ch10.co.il`

**Comment by Yaron10** [comment]
@mapx-,

Unfortunately that rule does not solve the problem.

Thank you.

**Comment by mapx-** [comment]
- strange, working fine on my side FF / chrome
- if you open the logger, do you see the filter above applied for `media` requests ? or are you getting some 3p media requests ?

**Comment by Yaron10** [comment]
@mapx-,

Thanks again. I appreciate your time.

I'm using Firefox 110 + uBO latest (reset to default settings, inc. EasyList Hebrew). 

https://ch10.co.il/news/807301/

Wrong:
![תמונה](https://user-images.githubusercontent.com/10229320/225030292-fc7b2c45-67b0-4aa6-adef-699fdf655b8a.png)

Commercial:
![תמונה](https://user-images.githubusercontent.com/10229320/225030512-71d3ba24-fe14-423b-bb00-ce183a28434e.png)


***

![תמונה](https://user-images.githubusercontent.com/10229320/225029969-87ac57df-d91e-48b2-a216-bd320a4810c7.png)

**Comment by mapx-** [comment]
- My filter is fixing "all the videos start with a commercial"
- "wrong" => even disabling uBO it's the same
- the video entirely commercial can be hidden using

`ch10.co.il##.fluid-width-video-wrapper`

**Comment by mapx-** [comment]
test

`ch10.co.il##.mejs-controls:style(visibility: visible !important)`

**Comment by Yaron10** [comment]
@mapx-,

Great.

So if I understand you correctly, there's no way to display the full video-thumbnail.

Anyway, I'd like to thank you again for the solution. 👍

**Comment by mapx-** [comment]
it's some glitch about cookies I guess. After watching one then it should be ok next time.
