### ISSUE TITLE
uBO supplement list

### ISSUE THREAD

**Issue by elig0n** [easylist/EasyListHebrew#373]
On uBO I need to add this additional list manually.
Could you please get it on the "Regions, Languages" list of the official plugin or connect the main one to it somehow ?

**Comment by IsraeliUser** [comment]
Specify your browser version + interface language, uBO version + lang, and OS.

According to my experience (Firefox, Chrome):
If your browser 'native' interface language is Hebrew, uBO interface language will be Hebrew, and EasyList Hebrew will be enabled by default.
If you just add a Hebrew language pack to Firefox, you will have to enable EasyList Hebrew manually.

If you are referring to `EasyListHebrew-uBO.txt` - it's automatically attached to the list at the beginning (by using `!#include EasyListHebrew-uBO.txt` in the main list). On _Filter lists_ tab, you can click on _view content_ (icon of an eye) to verify this.
