### ISSUE TITLE
block

### ISSUE THREAD

**Issue by shlomi284** [easylist/EasyListHebrew#376]
https://13tv.co.il/live/

**Comment by maxim-sm** [comment]
13tv appear to detect the adblocker on VOD as well (https://13tv.co.il/vod/).
Tested on desktop and mobile Firefox 96 with uBlock Origin 1.40.8

![screenshot_1](https://user-images.githubusercontent.com/17222086/151831037-2dcc6498-2ff3-462f-96f8-973ff73f16a4.png)

Thanks a lot for all your hard work!

**Comment by sha-265** [comment]
just add to your fitlers:
```
@@||securepubads.g.doubleclick.net/tag/js/gpt.js^$script,domain=13tv.co.il
```

**Comment by shlomi284** [comment]
> פשוט הוסף למסננים שלך:
> 
> ```
> @@||securepubads.g.doubleclick.net/tag/js/$script,domain=13tv.co.il
> ```

tnx king!
