### ISSUE TITLE
Some changes are needed

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [easylist/EasyListHebrew#379]
I want to add some cosmetic filters and fix some false positives.
@EasyListHebrew 
Please check your mail.

**Comment by EasyListHebrew** [comment]
Hey I didn't get anything please send to EasyListHebrew@gmail.com

**Comment by Hebrew-uBO-User** [comment]
Sent it again.
@EasyListHebrew 
Please check you _Spam_ folder...
