### ISSUE TITLE
www.inn.co.il: Prevent redirecting to ads

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#383]
Clear cookies.
https://www.inn.co.il/news/587412
Go to the comments section and upvote/downvote one.

Result:
You're redirected to an ad page.

Thank you.

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

Clear cookies.
The issue still exists.

Thank you.

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 
test `*$popup,domain=inn.co.il`

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

That doesn't work either.

Thank you.

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

I appreciate your work.
Unfortunately, the issue still exists.

**Comment by Hebrew-uBO-User** [comment]
@Yaron10 
I can reproduce on Chromium, but not on Firefox.
@mapx-

**Comment by Yaron10** [comment]
@Hebrew-uBO-User,

I'm using the latest Firefox and uBO.

Thank you.

**Comment by mapx-** [comment]
Does this filter help ?

`inn.co.il##+js(nowoif)`

**Comment by Yaron10** [comment]
@mapx-,

👍 
That rule solves the problem. I appreciate it.

Could you please have a look at https://github.com/easylist/EasyListHebrew/issues/360 when you have some free time?

Thank you.

@Hebrew-uBO-User,

Thanks again.
