### ISSUE TITLE
Block autoplay on Mako/other sites

### ISSUE THREAD

**Issue by PrivateiFox** [easylist/EasyListHebrew#386]
Mako seem to be using an autoplay framework(hola "spark" https://holaspark.com/faq - another example: https://forums.malwarebytes.com/topic/231385-resolved-false-positive-detection-of-playerh-cdncom-domain-%E2%9C%85/) to enable autoplay, and prevent regular ublock cosmetic filters from blocking video/audio/autoplay.

here's a filter that worked for me to stop this behaviour:
`||player.h-cdn.com`

I'm not sure whether it fits this filter list, but I think it might be helpful

**Comment by PrivateiFox** [comment]
`||rcs.mako.co.il/js/player`
this blocks the video player itself

**Comment by Hebrew-uBO-User** [comment]
@PrivateiFox 
`||player.h-cdn.com^`
breaks the video player when using an Israeli IP.
