### ISSUE TITLE
ads 13tv

### ISSUE THREAD

**Issue by shlomi284** [easylist/EasyListHebrew#387]
https://13tv.co.il/
new ads after refresh page

**Comment by Hebrew-uBO-User** [comment]
@shlomi284 
No ads on my end.
Do you mean
https://user-images.githubusercontent.com/28808501/101383696-2164d800-38c2-11eb-9897-f3f46ab21aac.png
?

@mapx-
It's a redirect page.
skip = דלג
Can it be fixed with uBO?

**Comment by shlomi284** [comment]
yes

**Comment by mapx-** [comment]
Test:

- clear cookies / storage for that site
- add:

`13tv.co.il##+js(cookie-remover, /^/)`

(initially maybe you should go with ctrl-f5 bypassing the cache)

**Comment by shlomi284** [comment]
I added it to my filters and it doesn't work

**Comment by EasyListHebrew** [comment]
@mapx- is it fixable or should i close?

**Comment by mapx-** [comment]
I cannot reproduce the issue on live page or some [article page](https://13tv.co.il/item/news/politics/security/jvo3w-904046916/)

**Comment by Hebrew-uBO-User** [comment]
I'm no longer able to reproduce the issue.
