### ISSUE TITLE
Haaretz.co.il & TherMarker.co.il - Can those filters be added?

### ISSUE THREAD

**Issue by BrightStar219** [easylist/EasyListHebrew#389]
They basically block the top and bottom of the site banners asking for payments.

haaretz.co.il##div>div>div:has([href*="https://promotions.haaretz.co.il/promotions-page"])
haaretz.co.il##div>div>div:has([href*="https://login.haaretz.co.il"])
themarker.com##div>div>div:has([href*="https://promotions.themarker.com/promotions-page"])
![29-03-2023_14-06-07414](https://user-images.githubusercontent.com/48417798/228514797-0ca15f1f-c51d-41a4-955c-86fccae14f5e.png)

**Comment by Hebrew-uBO-User** [comment]
@BrightStar219 
It's a Self-Promotion / Nag Message.
Filters should be add to _**Fanboy's Annoyance List**_ or _**uBlock₀ filters – Annoyances**_.
@ryanbr 
@mapx-
