### ISSUE TITLE
DNS EasyListHebrew?

### ISSUE THREAD

**Issue by bigplayer-ai** [easylist/EasyListHebrew#390]
DNS EasyListHebrew?

**Comment by Hebrew-uBO-User** [comment]
@bigplayer-ai 
https://github.com/easylist/EasyListHebrew/blob/master/adguard_hosts.txt
https://github.com/easylist/EasyListHebrew/blob/master/hosts.txt

**Comment by advertblocker** [comment]
@Alex-302
