### ISSUE TITLE
White screen in YNET mobile

### ISSUE THREAD

**Issue by yuriok82** [easylist/EasyListHebrew#391]
Iphone///Safari///https://www.ynet.co.il/

When I enter the YNET website, the mobile version, I see a white background and do not transfer news to the website for more than half a minute.

![IMG_0011](https://user-images.githubusercontent.com/114720212/231072623-f259f319-e2b2-4aa6-9bc0-5cd36e11d245.png)

**Comment by Hebrew-uBO-User** [comment]
@yuriok82 
What adblocker do you use?

EasyList Hebrew works best on uBlock Origin (uBO).
uBO is available for desktop devices (Chrome, Firefox, Edge, and Opera) and for mobile devices (Firefox for Android).

**Comment by katzelad** [comment]
> @yuriok82 What adblocker do you use?
> 
> EasyList Hebrew works best on uBlock Origin (uBO). uBO is available for desktop devices (Chrome, Firefox, Edge, and Opera) and for mobile devices (Firefox for Android).

I use uBlock Origin on Firefox for Android, and I get a blank page.

**Comment by Hebrew-uBO-User** [comment]
@mapx-
What do you suggest?

**Comment by mapx-** [comment]
No issue on my end on Firefox Android

**Comment by sha-265** [comment]
I have the same issue with uBlock Origin. With uBO **Lite** and EasyListHebrew enabled, there is no issue.

**Comment by Hebrew-uBO-User** [comment]
I can't reproduce. (Firefox for Android + uBO)
@mapx- 
What do you think?

@sha-265 
Can you isolate the problematic filter?
Enable the logger button: https://github.com/gorhill/uBlock/wiki/Advanced-settings#uipopupconfig

**Comment by sha-265** [comment]
@Hebrew-uBO-User can't find this logger in FF for Android. Anyway I opened an issue here: https://github.com/uBlockOrigin/uAssets/issues/22044. There is more relevant info there.

**Comment by sha-265** [comment]
```
ynet.co.il##^style#yitwall
```

works for me
