### ISSUE TITLE
ynet.co.il ad block detection & ads as background images

### ISSUE THREAD

**Issue by shaked6540** [easylist/EasyListHebrew#394]
Original issue: https://github.com/uBlockOrigin/uAssets/issues/18140#issuecomment-1555058988

--- 

### URL address of the web page

`https://www.ynet.co.il/vacation/israeltrips/article/h1l5rnhfrn`

### Category

ads

### Description

Started seeing ads on the side of the page, the ads are not clickable and I couldn't find them in element picker. I suspect its a background image

Upon inspecting the page I found this div, which seems to have some sort of a property for ad-block detection:
![image](https://github.com/uBlockOrigin/uAssets/assets/13851815/88609402-1bdc-4a14-b71a-7723014847ac)

It looks like it is a background image. Here is the link to it:
https://ynet-pic1.yit.co.il/picserver5/wcm_upload/2023/05/17/rkC0000BzSn/___.png

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/13851815/f3db6e4d-1dbf-4f8e-b6d9-d8e52bfd7c00)

**Comment by Hebrew-uBO-User** [comment]
@shaked6540 
I can't reproduce.

**Comment by shaked6540** [comment]
Alright
