### ISSUE TITLE
TheMarker/Haaretz anti-adblock problem

### ISSUE THREAD

**Issue by sha-265** [easylist/EasyListHebrew#401]
There is problem on some articles in TheMarker/Haaretz, that the ad-blocker is detected and the page is blocked.

Example:
https://www.themarker.com/advertising/2024-03-18/ty-article/0000018e-510f-dc34-a18e-f38f527a0000

I couldn't find the problematic filter, but when disable uBO for this websites, they are working as expected.

**Comment by Hebrew-uBO-User** [comment]
@sha-265 
Please update all your filter lists and test again.

**Comment by sha-265** [comment]
> @sha-265 Please update all your filter lists and test again.

@Hebrew-uBO-User still happening

**Comment by Hebrew-uBO-User** [comment]
@sha-265 
I can't reproduce. 
Please make a full report (with configuration data) using uBlock Origin and provide a link to the issue on uAssets.

**Comment by sha-265** [comment]
@Hebrew-uBO-User https://github.com/uBlockOrigin/uAssets/issues/23041

**Comment by EasyListHebrew** [comment]
not reproducible

**Comment by mderazon** [comment]
Same for me, seems to be working for everyone else ? I have nextdns as well with easy list Hebrew so not sure if it's conflicting

**Comment by sha-265** [comment]
@mderazon make sure you are not blocking `pagead2.googlesyndication.com`, that was my problem.

**Comment by EasyListHebrew** [comment]
are you a paid subscription?
isn't this website behind a paywall?

**Comment by sha-265** [comment]
This issue related to DNS based adblocking, not to EasyList.

**Comment by mderazon** [comment]
> make sure you are not blocking `pagead2.googlesyndication.com`, that was my problem.

This didn't seem to make a difference.

> are you a paid subscription? isn't this website behind a paywall?

Some of the articles are behind a paywall yes. 

> This issue related to DNS based adblocking, not to EasyList.

My problem is with their anti adblocking detection which I thought was covered by EasyListHebrew ? I am not sure.

On Chrome Android, with NextDNS it is not detecting ad-blockers and is working okay
On Firefox Android with ublock origin and EasyList + EasyListHebrew + couple of other lists it detects the adblocker

**Comment by Hebrew-uBO-User** [comment]
@mderazon 
I can't reproduce.
Disable DNS blocking and try again.
Try enabling DNS over HTTPS in your browser. I think it will bypass your DNS blocking.
If the problem persists, please report with uBO:
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website
https://github.com/gorhill/uBlock/wiki/The-"Report-a-filter-issue"-form

**Comment by shaked6540** [comment]
Happens to me as well. Also happens on a lot of other websites, like mako for example. A workaround is disabling javascript in ublock-origin. 

This is what I see instantly after clicking the link in the beginning of the issue: 
![image](https://github.com/user-attachments/assets/f506a5b4-ef52-4a61-8319-38a9e50bad37)


Started happening a lot more in the past week, had to disable javascript on a lot of websites.

(By blocking javascript I meant clicking on this button: 
![image](https://github.com/user-attachments/assets/0fe2714b-9423-4003-b114-8cd9efa77523)
)

**Comment by Hebrew-uBO-User** [comment]
@shaked6540 
I can't reproduce.
1. Clear cookies.
2. Disable DNS blocking and try again.
3. Try enabling DNS over HTTPS in your browser.
4. If the problem persists, please click on the "chat" icon and create a report:
https://github.com/gorhill/uBlock/wiki/The-"Report-a-filter-issue"-form

**Comment by shaked6540** [comment]
Seems like ublock origin is the one blocking it: 
![image](https://github.com/user-attachments/assets/6799e9cf-a1f4-495c-aa61-09150626380d)

Should I open an issue in the ublock repo?

**Comment by EasyListHebrew** [comment]
since we can't reproduce you can upload a list as picture or text of all the blocked elements
![image](https://github.com/user-attachments/assets/e892137b-0df3-44e6-a1e9-a6ee72715ea0)

**Comment by shaked6540** [comment]
Can confirm it works now, thanks a lot :)

**Comment by JStyle21** [comment]
Is it still working? i could not get it to work

**Comment by Hebrew-uBO-User** [comment]
@JStyle21 
I can't reproduce.
I need more details. Please read my previous comments.
