### ISSUE TITLE
Whitelist on Hebrew site

### ISSUE THREAD

**Issue by ozpacific** [easylist/EasyListHebrew#408]
When I want to login to online maccabi4u website, after login , it won't pass to open as it just goes back to login webpage.
It works fine when turn off adguard. Running from Adguard for windows 7.18.1.
online.maccabi4u.co.il
I don't see that adguard settings for adding a website to whitelist as to bypass adguard.

**Comment by Hebrew-uBO-User** [comment]
@ozpacific 
1. Report here: https://github.com/AdguardTeam/AdguardFilters/issues
2. Temporarily **disable** _Adguard For Windows_, and add _uBlock Origin_ to your browser. https://ublockorigin.com/
3. Can you reproduce this issue?
If so, open uBlock Origin's dashboard, and on "My filters" tab, add the following line:
`@@||report.maccabi.*/cls_report?$xmlhttprequest,domain=maccabi4u.co.il`
Tell me if it helps.
