### ISSUE TITLE
new ap

### ISSUE THREAD

**Issue by shlomi284** [easylist/EasyListHebrew#409]
https://13tv.co.il/
when click on  some
![image](https://github.com/user-attachments/assets/a737e683-b98b-4728-abca-6bf17333efb1)

**Comment by shlomi284** [comment]
> עובד בסדר גמור בצד שלי עם EasyListHebrew, <img alt="צילום מסך 2024-08-02 ב-20 49 04" width="1455" src="https://private-user-images.githubusercontent.com/175205139/354681178-56acb015-4bd8-4bdd-8519-deecef27c0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDY4ODIsIm5iZiI6MTcyMjcwNjU4MiwicGF0aCI6Ii8xNzUyMDUxMzkvMzU0NjgxMTc4LTU2YWNiMDE1LTRiZDgtNGJkZC04NTE5LWRlZWNlZjI3YzBjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNzM2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzZhM2EyMDVhYTA3NDA1NmQ5MWU4MjRiNWE1NDFkY2UzM2ZjZDZiMDg3MjJhNjcwZmI0NzVmMDYyZGFlZGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UqZBM5SX2D_o-6z2V6PlSQqQUvByYJXuA_pPBdubUU8">
> 
> עם זאת יש לי מסנן מותאם אישית להסרת המודעות המובילות (לא קשור לבעיה)
> 
> 13tv.co.il##.czNrTD.TopBannerstyles__Container-sc-1alob2s-1

**Comment by shlomi284** [comment]
Have you tried clicking on any article?

**Comment by Hebrew-uBO-User** [comment]
@shlomi284 
I fixed it. Thanks for reporting.

**Comment by shlomi284** [comment]
tnx
