### ISSUE TITLE
Make the rotter.net web version (https://rotter.net/forum/listforum.php) much cleaner

### ISSUE THREAD

**Issue by lakdif** [easylist/EasyListHebrew#410]
rotter.net##tr:nth-of-type(6)
rotter.net##tr:nth-of-type(13)
rotter.net##tr:nth-of-type(16)
rotter.net##tr:nth-of-type(24)
rotter.net##tr:nth-of-type(36)
rotter.net##[href^="https://www.booking.com/index.html"]
rotter.net###taboola-below-article-thumbnails
rotter.net##center > table > tbody
rotter.net##body > table:nth-of-type(1) > tbody
rotter.net##body > table:nth-of-type(2) > tbody > tr:nth-of-type(2) > td

Before:
<img width="1502" alt="Screenshot 2024-08-02 at 20 26 49" src="https://github.com/user-attachments/assets/70d9c49d-b798-4495-beec-7498bb09c942">

After:
<img width="1506" alt="Screenshot 2024-08-02 at 20 27 12" src="https://github.com/user-attachments/assets/55b747ae-9082-4e16-97e0-15ec7c5fe567">

Also when clicking on the post, it's usually full of ads (I use NextDNS so you see a blank space, but this is an ad
container that should be removed)

Before:
<img width="1500" alt="Screenshot 2024-08-02 at 20 37 14" src="https://github.com/user-attachments/assets/656ecef3-604c-4927-8233-080f207c3eaa">

After:
<img width="1503" alt="Screenshot 2024-08-02 at 20 37 29" src="https://github.com/user-attachments/assets/037b0770-e5a3-45fe-9bbe-bcfc823a4596">

**Comment by Hebrew-uBO-User** [comment]
@lakdif 
I can't reproduce. The only ad I can see is for _Booking_.

`###taboola-below-article-thumbnails` is included in EasyList as a generic cosmetic filter.

1. Make sure you're using ***all*** of uBO's selected-by-default filter lists. https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists 
2. Make sure option "Ignore generic cosmetic filters" is ***not*** selected. It's uBO defaults for desktop devices.
3. Use a DNS ***without*** ad-filtering (such as `1.1.1.1`, `8.8.8.8` or `9.9.9.9`)
