### ISSUE TITLE
13tv.co.il - remove top ads

### ISSUE THREAD

**Issue by lakdif** [easylist/EasyListHebrew#411]
13tv.co.il##.czNrTD.TopBannerstyles__Container-sc-1alob2s-1

**Comment by Hebrew-uBO-User** [comment]
@lakdif 
I've added `13tv.co.il##[class^="TopBannerstyles_"]` two days ago.
https://github.com/easylist/EasyListHebrew/commit/d16c2653aecd81d4b68f674b4a405c23adbb8ea2
