### ISSUE TITLE
Issue with Ad Blocking on Mako - Audio of Ads Plays in the Background Despite Visual Block

### ISSUE THREAD

**Issue by Saviormaker** [easylist/EasyListHebrew#416]
Hello,

I am experiencing an issue with the ad blocking functionality on the **[Mako](mako.co.il)** website. When I try to watch a series, the visual component of the ad is successfully blocked; however, the audio of the ad continues to play in the background.

More specifically, the video of the series stops, and I can still hear the ad’s audio even though the visual element is not displayed. Additionally, it is possible to resume the series, but the ad audio continues to play simultaneously in the background, disrupting the viewing experience.

Could you please investigate and provide a solution for this issue?

Thank you in advance for your support.

**Comment by Hebrew-uBO-User** [comment]
@Saviormaker 
I can't reproduce. (Firefox + uBlock Origin)
Please specify your adblocker and browser.
Use uBlock Origin: https://ublockorigin.com/
Make a full report: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website

@sha-265 
Can you reproduce this issue?

**Comment by sha-265** [comment]
> Can you reproduce this issue?

Nope.
