### ISSUE TITLE
kikar.co.il is ad-riddled

### ISSUE THREAD

**Issue by Halbour** [easylist/EasyListHebrew#420]
The site mentioned above, kikar.co.il , is just full of ads and constant pop-ups - even when uBO is active and the filterlist is being used.

**Comment by Hebrew-uBO-User** [comment]
Fixed: https://github.com/easylist/EasyListHebrew/commit/6551a3016bb44e4e34648815869a40081f296ec8

**Comment by Halbour** [comment]
It's much better now, but ads still popup:
![image](https://github.com/user-attachments/assets/97bbc518-26fa-4bb3-b7db-148b0f110f2c)

**Comment by tzagim** [comment]
@Halbour

I can't reproduce it.

Could you try reloading the list and checking again?

**Comment by Hebrew-uBO-User** [comment]
@Halbour 
I can't reproduce.

**Comment by Halbour** [comment]
Somehow, after updating the list *again,* I can now confirm it's gone.
