### ISSUE TITLE
can't use http://www.yesplanet.co.il

### ISSUE THREAD

**Issue by EasyListHebrew** [easylist/EasyListHebrew#5]
_From @talregev on May 19, 2014 16:25_

when i disable adblock at yesplanet.co.il, there is a ads, but i can search for movie. (can write text at search box).
when i active adblock, i can't search for movie.

can you fix that?

Tal. 

_Copied from original issue: ABPIsrael/EasyListHebrew#6_

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on May 19, 2014 16:58_

looks good to me
what browser are you using?
can you send a report?

**Comment by EasyListHebrew** [comment]
_From @talregev on May 19, 2014 17:7_

Sometimes it working good, and sometimes not :(.
now it working for me.
i am using chrome Version 34.0.1847.137 m
adblock: v2.6.34.

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on May 26, 2014 7:2_

try adding this
@@||pas-rahav.com^$domain=yesplanet.co.il

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on June 17, 2014 9:1_

looks good

**Comment by EasyListHebrew** [comment]
_From @talregev on November 3, 2014 18:33_

can you add this?
www.yesplanet.co.il##DIV[id="snatch"]
this solve the problem for me

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on November 3, 2014 18:44_

better 
yesplanet.co.il###snatch

**Comment by EasyListHebrew** [comment]
_From @talregev on November 3, 2014 18:47_

you will added to official list?

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on November 3, 2014 18:48_

already did
https://github.com/AdBlockPlusIsrael/EasyListHebrew/commit/4b9016011ffd443b27c81e2353f4fa619d1bdfe5

**Comment by EasyListHebrew** [comment]
This issue was moved to abpisrael/easylisthebrew#5

**Comment by EasyListHebrew** [comment]
This issue was moved to ABPIsrael/EasyListHebrew#5

**Comment by talregev** [comment]
Can you add this?
www.yesplanet.co.il##DIV[id="snatchbg"]
